const crypto = require('node:crypto');
const mongoose = require('mongoose');
const {
  BackupIntegrityManifest,
  BackupManifest,
  CacheInvalidationEvent,
  DisasterRecoveryDrill,
  DisasterRecoveryPolicy,
  DisasterRecoveryRestore,
  OperationalIncident,
  ProjectionMetadata,
  QueuePartition,
  RegionalAuthorityTransition,
  RegionalDeploymentConfiguration,
  RegionalFailoverPlan,
  RegionalHealthSnapshot,
  RegionalReplicationHealth,
  RegionalRoutingDecision,
  RegionalServiceRegistration,
  RegionalWriteAuthority,
  WorkerRegistration,
} = require('../models');
const { createAuditLog } = require('./auditService');
const { assertOperationalAccess } = require('./operationalState.service');
const { assertAuthorized, actorFromPartner } = require('./authorization.service');
const { createInvalidationEvent } = require('./dataAccessProjection.service');
const approvalService = require('./approval.service');
const authorityService = require('./regionalAuthority.service');
const core = require('./regionalResilienceCore.service');
const metrics = require('./regionalResilienceMetrics.service');
const { MockBackupAdapter, NoopBackupAdapter } = require('./regionalBackupAdapters.service');
const { AppError } = require('../utils/AppError');
const { canonicalize } = require('../utils/idempotency');

function idOf(value) { return String(value?._id || value?.id || value || '').trim(); }
function plain(value) { return value && (typeof value.toObject === 'function' ? value.toObject() : { ...value }); }
function actorId(caller = {}) { return `partner:${idOf(caller.partner?._id)}`; }
function scopeFrom(input = {}, caller = {}, workspaceRequired = true) {
  const partnerId = idOf(caller.partner?._id);
  const organizationId = core.safeIdentifier(input.organizationId || partnerId, 'organizationId');
  if (partnerId && organizationId !== partnerId) throw new AppError(403, 'AUTHORIZATION_DENIED', 'Authorization denied.');
  return { organizationId, workspaceId: core.safeIdentifier(input.workspaceId || input.receivingWorkspaceId, 'workspaceId', workspaceRequired), partnerId, actorId: actorId(caller), actorType: 'service_account', requestId: core.safeIdentifier(caller.requestId || input.requestId || `request-${crypto.randomUUID()}`, 'requestId'), traceId: core.safeIdentifier(caller.traceId || input.traceId || `trace-${crypto.randomUUID()}`, 'traceId') };
}
function scopeKey(scope, requestedScope = 'workspace') { return requestedScope === 'platform' ? 'platform' : requestedScope === 'organization' ? `organization:${scope.organizationId}` : `organization:${scope.organizationId}:workspace:${scope.workspaceId}`; }
function paging(input = {}) { const limit = core.boundedInteger(input.limit, 'limit', 1, 100, 50); const page = core.boundedInteger(input.page, 'page', 1, 100_000, 1); return { limit, page, skip: (page - 1) * limit }; }
function dependencies(overrides = {}) { return { BackupIntegrityManifest, BackupManifest, CacheInvalidationEvent, DisasterRecoveryDrill, DisasterRecoveryPolicy, DisasterRecoveryRestore, OperationalIncident, ProjectionMetadata, QueuePartition, RegionalAuthorityTransition, RegionalDeploymentConfiguration, RegionalFailoverPlan, RegionalHealthSnapshot, RegionalReplicationHealth, RegionalRoutingDecision, RegionalServiceRegistration, RegionalWriteAuthority, WorkerRegistration, assertOperationalAccess, assertAuthorized, audit: createAuditLog, createInvalidationEvent, createApprovalRequest: approvalService.createApprovalRequest, enforceApproval: approvalService.enforceApproval, consumeApprovalGrants: approvalService.consumeApprovalGrants, backupAdapter: process.env.REGIONAL_BACKUP_ADAPTER === 'mock' ? new MockBackupAdapter() : new NoopBackupAdapter(), ...overrides }; }
async function authorize(permission, type, resourceId, scope, caller, context = {}, deps = dependencies()) { return deps.assertAuthorized(actorFromPartner(caller.partner, { organizationId: scope.organizationId, workspaceId: scope.workspaceId }), permission, { type, id: idOf(resourceId || scope.workspaceId || scope.organizationId), organizationId: scope.organizationId, workspaceId: scope.workspaceId }, { requestId: scope.requestId, traceId: scope.traceId, regionalResilience: context }); }
async function audit(action, type, resourceId, scope, metadata = {}, deps = dependencies()) { core.assertNoSensitiveData(metadata); return deps.audit(scope.actorType, scope.actorId, action, type, idOf(resourceId), { organizationId: scope.organizationId, workspaceId: scope.workspaceId, ...metadata }, { requestId: scope.requestId, traceId: scope.traceId }); }
function mutationDigests(input, purpose, key) { const idempotencyKey = core.safeIdentifier(input.idempotencyKey, 'idempotencyKey', false); if (!idempotencyKey) return {}; const material = { ...input }; delete material.idempotencyKey; delete material.requestId; delete material.traceId; return { idempotencyKeyHash: `sha256:${crypto.createHash('sha256').update(`${purpose}:${key}:${idempotencyKey}`).digest('hex')}`, requestFingerprint: `sha256:${crypto.createHash('sha256').update(canonicalize(material)).digest('hex')}` }; }
function assertReplay(record, digests) { if (record.requestFingerprint !== digests.requestFingerprint) throw new AppError(409, 'IDEMPOTENCY_CONFLICT', 'Idempotency key is bound to another regional resilience mutation.'); return record; }
function objectId(value, path) { if (!mongoose.isValidObjectId(value)) throw new AppError(400, 'REGIONAL_RESILIENCE_VALIDATION_FAILED', 'Regional resilience validation failed.', [{ path, message: `${path} must be valid.` }]); return value; }
function serialize(record) { if (!record) return null; const value = plain(record); delete value.idempotencyKeyHash; delete value.requestFingerprint; delete value.__v; value.id = idOf(value); delete value._id; return value; }
function scopeFilter(scope) { return { organizationId: scope.organizationId, ...(scope.workspaceId ? { workspaceId: scope.workspaceId } : {}) }; }
async function operationalGuard(scope, deps, operation) { return deps.assertOperationalAccess({ organizationId: scope.organizationId, partnerId: scope.partnerId, workspaceId: scope.workspaceId, operation }); }
function approvalAction(record, scope, permission, resourceType, authorization, approvalRequestId) {
  const isFailover = resourceType === 'RegionalFailoverPlan';
  return {
    organizationId: scope.organizationId,
    workspaceId: scope.workspaceId,
    requesterActorId: record.requestedBy,
    requesterActorType: 'service_account',
    permission,
    resourceType,
    resourceId: idOf(record),
    operationType: permission,
    approvalRequestId,
    policySnapshotRevision: authorization?.policySnapshotRevision,
    safeRequestAttributes: isFailover
      ? { sourceRegionId: record.sourceRegionId, targetRegionId: record.targetRegionId, sourceAuthorityEpoch: record.sourceAuthorityEpoch, targetAuthorityEpoch: record.targetAuthorityEpoch, potentialDataLoss: record.potentialDataLoss }
      : { backupId: record.backupId, targetRegionId: record.targetRegionId, integrityStatus: record.integrityStatus, migrationStatus: record.migrationStatus, indexStatus: record.indexStatus },
  };
}
async function requestApproval(record, scope, caller, permission, resourceType, deps) {
  try {
    return await deps.createApprovalRequest({
      organizationId: scope.organizationId,
      workspaceId: scope.workspaceId,
      requesterActorId: record.requestedBy,
      requesterActorType: 'service_account',
      permission,
      resourceType,
      resourceId: idOf(record),
      operationType: permission,
      safeRequestAttributes: approvalAction(record, scope, permission, resourceType).safeRequestAttributes,
      idempotencyKey: `regional-approval:${resourceType}:${idOf(record)}:${permission}`,
      reason: `${resourceType} requires governed approval.`,
    }, caller);
  } catch (error) {
    if (['APPROVAL_REQUIRED', 'APPROVAL_POLICY_REQUIRED'].includes(error?.code)) return null;
    throw error;
  }
}

async function createVersioned(kind, input, caller, options = {}) {
  core.assertNoSensitiveData(input); const deps = dependencies(options.dependencies); const model = kind === 'configuration' ? deps.RegionalDeploymentConfiguration : deps.DisasterRecoveryPolicy; const permission = kind === 'configuration' ? 'regionalConfiguration.create' : 'disasterRecoveryPolicy.create'; const type = kind === 'configuration' ? 'RegionalDeploymentConfiguration' : 'DisasterRecoveryPolicy'; const requestedScope = input.scope || 'workspace'; const scope = scopeFrom(input, caller, requestedScope === 'workspace'); await authorize(permission, type, null, scope, caller, { requestedAction: `${kind}_create` }, deps); await deps.assertOperationalAccess({ organizationId: scope.organizationId, partnerId: scope.partnerId, workspaceId: scope.workspaceId, operation: 'PRIVILEGED_CONFIGURATION' }); const key = scopeKey(scope, requestedScope); const digests = mutationDigests(input, kind, key);
  if (digests.idempotencyKeyHash) { const replay = await model.findOne({ scopeKey: key, idempotencyKeyHash: digests.idempotencyKeyHash }).select('+idempotencyKeyHash +requestFingerprint'); if (replay) return serialize(assertReplay(replay, digests)); }
  const latest = await model.findOne({ scopeKey: key, name: String(input.name || '').trim() }).sort({ version: -1 }).lean(); const normalized = kind === 'configuration' ? core.normalizeRegionalConfiguration({ ...input, version: input.version || Number(latest?.version || 0) + 1, status: 'draft' }) : core.normalizeDisasterRecoveryPolicy({ ...input, version: input.version || Number(latest?.version || 0) + 1, status: 'draft' });
  const record = await model.create({ ...normalized, ...digests, scope: requestedScope, scopeKey: key, ...(requestedScope !== 'platform' ? { organizationId: scope.organizationId } : {}), ...(requestedScope === 'workspace' ? { workspaceId: scope.workspaceId } : {}), createdBy: scope.actorId, updatedBy: scope.actorId }); await audit(`regional.${kind}.created`, type, record, scope, { version: record.version, status: record.status }, deps); return serialize(record);
}

async function listVersioned(kind, input, caller, options = {}) { const deps = dependencies(options.dependencies); const model = kind === 'configuration' ? deps.RegionalDeploymentConfiguration : deps.DisasterRecoveryPolicy; const permission = kind === 'configuration' ? 'regionalConfiguration.read' : 'disasterRecoveryPolicy.read'; const type = kind === 'configuration' ? 'RegionalDeploymentConfiguration' : 'DisasterRecoveryPolicy'; const scope = scopeFrom(input, caller, false); await authorize(permission, type, null, scope, caller, {}, deps); const { limit, page, skip } = paging(input); const keys = [`organization:${scope.organizationId}`, ...(scope.workspaceId ? [`organization:${scope.organizationId}:workspace:${scope.workspaceId}`] : []), ...(String(input.includePlatform) === 'true' ? ['platform'] : [])]; const filter = { scopeKey: { $in: keys }, ...(input.status ? { status: input.status } : {}) }; const [items, total] = await Promise.all([model.find(filter).sort({ scopeKey: 1, name: 1, version: -1 }).skip(skip).limit(limit).lean(), model.countDocuments(filter)]); return { items: items.map(serialize), page, limit, total }; }
async function scopedVersioned(model, id, scope, notFoundCode) { objectId(id, 'id'); const record = await model.findOne({ _id: id, $or: [{ organizationId: scope.organizationId, workspaceId: scope.workspaceId }, { organizationId: scope.organizationId, workspaceId: { $exists: false } }, { scopeKey: 'platform' }] }); if (!record) throw new AppError(404, notFoundCode, 'Regional resilience record was not found.'); return record; }
async function getVersioned(kind, id, input, caller, options = {}) { const deps = dependencies(options.dependencies); const model = kind === 'configuration' ? deps.RegionalDeploymentConfiguration : deps.DisasterRecoveryPolicy; const permission = kind === 'configuration' ? 'regionalConfiguration.read' : 'disasterRecoveryPolicy.read'; const type = kind === 'configuration' ? 'RegionalDeploymentConfiguration' : 'DisasterRecoveryPolicy'; const scope = scopeFrom(input, caller, false); await authorize(permission, type, id, scope, caller, {}, deps); return serialize(await scopedVersioned(model, id, scope, kind === 'configuration' ? 'REGIONAL_CONFIGURATION_NOT_FOUND' : 'DISASTER_RECOVERY_POLICY_NOT_FOUND')); }
async function mutateVersioned(kind, action, id, input, caller, options = {}) { core.assertNoSensitiveData(input); const deps = dependencies(options.dependencies); const model = kind === 'configuration' ? deps.RegionalDeploymentConfiguration : deps.DisasterRecoveryPolicy; const prefix = kind === 'configuration' ? 'regionalConfiguration' : 'disasterRecoveryPolicy'; const type = kind === 'configuration' ? 'RegionalDeploymentConfiguration' : 'DisasterRecoveryPolicy'; const scope = scopeFrom(input, caller, false); await authorize(`${prefix}.${action}`, type, id, scope, caller, { requestedAction: `${kind}_${action}` }, deps); await operationalGuard(scope, deps, 'PRIVILEGED_CONFIGURATION'); const record = await scopedVersioned(model, id, scope, kind === 'configuration' ? 'REGIONAL_CONFIGURATION_NOT_FOUND' : 'DISASTER_RECOVERY_POLICY_NOT_FOUND');
  if (action === 'update') { if (record.status !== 'draft') throw new AppError(409, kind === 'configuration' ? 'REGIONAL_CONFIGURATION_IMMUTABLE' : 'DISASTER_RECOVERY_POLICY_IMMUTABLE', 'Active and archived versions are immutable.'); const normalized = kind === 'configuration' ? core.normalizeRegionalConfiguration({ ...plain(record), ...input, version: record.version, status: 'draft' }) : core.normalizeDisasterRecoveryPolicy({ ...plain(record), ...input, version: record.version, status: 'draft' }); Object.assign(record, normalized, { updatedBy: scope.actorId }); }
  if (action === 'validate') { const result = kind === 'configuration' ? core.validateRegionalConfiguration(plain(record)) : core.validateDisasterRecoveryPolicy(plain(record)); record.validation = { valid: result.valid, safeReasonCodes: result.safeReasonCodes, validatedAt: new Date() }; if (!result.valid) { await record.save(); return { ...serialize(record), validation: result }; } }
  if (action === 'activate') { if (record.status !== 'draft') throw new AppError(409, kind === 'configuration' ? 'REGIONAL_CONFIGURATION_IMMUTABLE' : 'DISASTER_RECOVERY_POLICY_IMMUTABLE', 'Only drafts may be activated.'); const result = kind === 'configuration' ? core.validateRegionalConfiguration(plain(record)) : core.validateDisasterRecoveryPolicy(plain(record)); if (!result.valid) throw new AppError(409, kind === 'configuration' ? 'REGIONAL_CONFIGURATION_INVALID' : 'DISASTER_RECOVERY_POLICY_INVALID', 'The record must pass validation before activation.', result.errors || []); await model.updateMany({ scopeKey: record.scopeKey, name: record.name, status: 'active', _id: { $ne: record._id } }, { $set: { status: 'archived', archivedAt: new Date(), archivedBy: scope.actorId } }); record.status = 'active'; record.validation = { valid: true, safeReasonCodes: [], validatedAt: new Date() }; record.activatedBy = scope.actorId; record.activatedAt = new Date(); if (kind === 'configuration') await deps.QueuePartition.updateMany({ $or: [{ activeRegionId: { $exists: false } }, { activeRegionId: null }] }, { $set: { homeRegionId: record.preferredPrimaryRegionId, activeRegionId: record.preferredPrimaryRegionId, fallbackRegionIds: record.permittedFailoverRegionIds, regionalStatus: 'active' }, $inc: { regionalOwnershipEpoch: 1 } }); }
  if (action === 'archive') { if (record.status === 'archived') return serialize(record); record.status = 'archived'; record.archivedBy = scope.actorId; record.archivedAt = new Date(); }
  await record.save(); await audit(`regional.${kind}.${action === 'update' ? 'updated' : `${action}d`}`, type, record, scope, { version: record.version, status: record.status }, deps); return serialize(record);
}

const createConfiguration = (input, caller, options) => createVersioned('configuration', input, caller, options);
const listConfigurations = (input, caller, options) => listVersioned('configuration', input, caller, options);
const getConfiguration = (id, input, caller, options) => getVersioned('configuration', id, input, caller, options);
const updateConfiguration = (id, input, caller, options) => mutateVersioned('configuration', 'update', id, input, caller, options);
const validateConfiguration = (id, input, caller, options) => mutateVersioned('configuration', 'validate', id, input, caller, options);
const activateConfiguration = (id, input, caller, options) => mutateVersioned('configuration', 'activate', id, input, caller, options);
const archiveConfiguration = (id, input, caller, options) => mutateVersioned('configuration', 'archive', id, input, caller, options);
const createDrPolicy = (input, caller, options) => createVersioned('policy', input, caller, options);
const listDrPolicies = (input, caller, options) => listVersioned('policy', input, caller, options);
const getDrPolicy = (id, input, caller, options) => getVersioned('policy', id, input, caller, options);
const updateDrPolicy = (id, input, caller, options) => mutateVersioned('policy', 'update', id, input, caller, options);
const validateDrPolicy = (id, input, caller, options) => mutateVersioned('policy', 'validate', id, input, caller, options);
const activateDrPolicy = (id, input, caller, options) => mutateVersioned('policy', 'activate', id, input, caller, options);
const archiveDrPolicy = (id, input, caller, options) => mutateVersioned('policy', 'archive', id, input, caller, options);

async function activeConfiguration(scope, deps) { const keys = [...(scope.workspaceId ? [`organization:${scope.organizationId}:workspace:${scope.workspaceId}`] : []), `organization:${scope.organizationId}`, 'platform']; return deps.RegionalDeploymentConfiguration.findOne({ scopeKey: { $in: keys }, status: 'active' }).sort({ workspaceId: -1, organizationId: -1, version: -1 }).lean(); }
async function activeDrPolicy(scope, deps) { const keys = [...(scope.workspaceId ? [`organization:${scope.organizationId}:workspace:${scope.workspaceId}`] : []), `organization:${scope.organizationId}`, 'platform']; return deps.DisasterRecoveryPolicy.findOne({ scopeKey: { $in: keys }, status: 'active' }).sort({ workspaceId: -1, organizationId: -1, version: -1 }).lean(); }

async function listRegions(input = {}, caller = {}, options = {}) {
  const deps = dependencies(options.dependencies); const scope = scopeFrom(input, caller, false); await authorize('regionalResilience.read', 'RegionalDeploymentConfiguration', null, scope, caller, {}, deps); const configuration = await activeConfiguration(scope, deps); if (!configuration) return { items: [], authority: null, generatedAt: new Date() };
  const authority = await getAuthorityForScope(scope, deps);
  const health = await deps.RegionalHealthSnapshot.aggregate([{ $match: { regionId: { $in: configuration.regions.map((region) => region.regionId) } } }, { $sort: { snapshotAt: -1 } }, { $group: { _id: '$regionId', item: { $first: '$$ROOT' } } }]);
  const healthByRegion = new Map(health.map((entry) => [entry._id, entry.item]));
  const services = await deps.RegionalServiceRegistration.aggregate([{ $match: { regionId: { $in: configuration.regions.map((region) => region.regionId) }, state: { $in: ['active', 'idle', 'degraded'] } } }, { $group: { _id: '$regionId', count: { $sum: 1 }, workers: { $sum: { $cond: [{ $in: ['$serviceType', ['execution_worker', 'recovery_worker', 'control_plane_worker', 'projection_worker']] }, 1, 0] } } } }]); const serviceByRegion = new Map(services.map((entry) => [entry._id, entry]));
  return { configurationId: idOf(configuration), configurationVersion: configuration.version, items: configuration.regions.map((region) => ({ ...region, health: serialize(healthByRegion.get(region.regionId)), healthyServiceCount: serviceByRegion.get(region.regionId)?.count || 0, activeWorkerCount: serviceByRegion.get(region.regionId)?.workers || 0, writeAuthority: authority?.activeRegionId === region.regionId, authorityEpoch: authority?.authorityEpoch || 0 })), authority: serialize(authority), generatedAt: new Date() };
}

async function getRegion(regionId, input = {}, caller = {}, options = {}) { const result = await listRegions(input, caller, options); const region = result.items.find((item) => item.regionId === regionId); if (!region) throw new AppError(404, 'REGION_NOT_FOUND', 'Region was not found.'); return { ...region, generatedAt: result.generatedAt }; }

async function controlRegion(regionId, action, input = {}, caller = {}, options = {}) {
  core.assertNoSensitiveData(input); const deps = dependencies(options.dependencies); const scope = scopeFrom(input, caller, false); const permissions = { isolate: 'regionalOperations.isolate', unisolate: 'regionalOperations.unisolate', drain: 'regionalOperations.drain', resume: 'regionalOperations.resume', freeze_writes: 'regionalOperations.freezeWrites', evaluate_health: 'regionalResilience.readHealth' }; await authorize(permissions[action], 'RegionalServiceRegistration', regionId, scope, caller, { requestedAction: action }, deps); await operationalGuard(scope, deps, action === 'evaluate_health' ? 'HEALTH' : 'INCIDENT_RESPONSE'); const configuration = await activeConfiguration(scope, deps); const region = configuration?.regions?.find((entry) => entry.regionId === regionId); if (!region) throw new AppError(404, 'REGION_NOT_FOUND', 'Region was not found.'); const now = new Date();
  if (action === 'evaluate_health') return evaluateRegionHealth(regionId, input, caller, { ...options, dependencies: deps });
  const state = { isolate: 'isolated', unisolate: 'starting', drain: 'draining', resume: 'idle' }[action];
  if (state) await deps.RegionalServiceRegistration.updateMany({ regionId }, { $set: { state, ...(action === 'drain' ? { drainRequestedAt: now } : {}), ...(action === 'resume' ? { lastReadyAt: now } : {}) } });
  if (action === 'freeze_writes') { const authority = await deps.RegionalWriteAuthority.findOne({ activeRegionId: regionId, ...scopeFilter(scope) }); if (authority) await authorityService.freezeAuthority({ scope: authority.scope, organizationId: authority.organizationId, workspaceId: authority.workspaceId, regionId, authorityEpoch: authority.authorityEpoch }, { dependencies: deps, now }); }
  await audit(`regional.region.${action}`, 'RegionalServiceRegistration', regionId, scope, { regionId, safeReasonCode: input.safeReasonCode || `REGION_${action.toUpperCase()}` }, deps); return { regionId, state: action === 'freeze_writes' ? 'write_frozen' : state, changedAt: now };
}

async function evaluateRegionHealth(regionId, input = {}, caller = {}, options = {}) {
  const deps = dependencies(options.dependencies); const scope = scopeFrom(input, caller, false); const now = options.now || new Date(); const configuration = await activeConfiguration(scope, deps); const region = configuration?.regions?.find((entry) => entry.regionId === regionId); if (!region) throw new AppError(404, 'REGION_NOT_FOUND', 'Region was not found.'); const services = await deps.RegionalServiceRegistration.find({ regionId }).lean(); const cutoff = new Date(now.getTime() - configuration.regionalHealthTimeoutMs); const healthy = services.filter((service) => ['active', 'idle'].includes(service.state) && new Date(service.heartbeatAt) > cutoff); const unavailable = services.filter((service) => ['unhealthy', 'stopped', 'isolated'].includes(service.state) || new Date(service.heartbeatAt) <= cutoff); const status = unavailable.length === services.length && services.length ? 'unavailable' : unavailable.length ? 'degraded' : healthy.length ? 'healthy' : 'unknown'; const replication = await deps.RegionalReplicationHealth.findOne({ targetRegionId: regionId }).sort({ generatedAt: -1 }).lean(); const authority = await deps.RegionalWriteAuthority.findOne({ activeRegionId: regionId }).lean(); const categories = Object.fromEntries(['serviceHealthCategory', 'databaseHealthCategory', 'replicationHealthCategory', 'cacheHealthCategory', 'queueHealthCategory', 'workerHealthCategory', 'gatewayHealthCategory'].map((field) => [field, field === 'replicationHealthCategory' ? replication?.status || 'unknown' : status === 'healthy' ? 'healthy' : status === 'unavailable' ? 'unavailable' : 'degraded'])); const snapshot = await deps.RegionalHealthSnapshot.create({ regionId, snapshotAt: now, status, ...categories, healthyServiceCount: healthy.length, degradedServiceCount: Math.max(0, services.length - healthy.length - unavailable.length), unavailableServiceCount: unavailable.length, activeWorkerCount: healthy.filter((service) => service.serviceType.endsWith('worker')).length, queuedWorkCategory: 'unknown', oldestQueueAgeCategory: 'unknown', replicationLagCategory: replication?.lagCategory || 'unknown', measuredReplicationLagMs: replication?.lagMs, lastConfirmedWriteAt: replication?.lastSuccessfulWriteAt, lastConfirmedReadAt: replication?.lastSuccessfulReadAt, writeAuthorityEpoch: authority?.authorityEpoch || 0, authorityLeaseHealth: !authority ? 'missing' : new Date(authority.leaseExpiresAt) <= now ? 'expired' : 'healthy', safeReasonCodes: [status === 'healthy' ? 'REGION_HEALTHY' : `REGION_${status.toUpperCase()}`], generatedAt: now, expiresAt: new Date(now.getTime() + configuration.regionalHealthTimeoutMs) }); metrics.gauge('regional_health', { healthCategory: status }, 1); return serialize(snapshot);
}

async function getHealth(input = {}, caller = {}, options = {}) { const deps = dependencies(options.dependencies); const scope = scopeFrom(input, caller, false); await authorize('regionalResilience.readHealth', 'RegionalHealthSnapshot', null, scope, caller, {}, deps); const configuration = await activeConfiguration(scope, deps); if (!configuration) return { items: [], generatedAt: new Date() }; const items = await deps.RegionalHealthSnapshot.find({ regionId: { $in: configuration.regions.map((region) => region.regionId) } }).sort({ snapshotAt: -1 }).limit(100).lean(); return { items: items.map(serialize), generatedAt: new Date() }; }
async function getReplication(input = {}, caller = {}, options = {}) { const deps = dependencies(options.dependencies); const scope = scopeFrom(input, caller, false); await authorize('regionalResilience.readReplication', 'RegionalReplicationHealth', null, scope, caller, {}, deps); const configuration = await activeConfiguration(scope, deps); if (!configuration) return { items: [], generatedAt: new Date() }; const ids = configuration.regions.map((region) => region.regionId); const items = await deps.RegionalReplicationHealth.find({ sourceRegionId: { $in: ids }, targetRegionId: { $in: ids } }).sort({ generatedAt: -1 }).limit(100).lean(); return { items: items.map(serialize), generatedAt: new Date() }; }

async function getWriteAuthority(input = {}, caller = {}, options = {}) { const deps = dependencies(options.dependencies); const scope = scopeFrom(input, caller, false); await authorize('regionalResilience.readDetails', 'RegionalWriteAuthority', null, scope, caller, {}, deps); const keys = [...(scope.workspaceId ? [`organization:${scope.organizationId}:workspace:${scope.workspaceId}`] : []), `organization:${scope.organizationId}`, 'platform']; return serialize(await deps.RegionalWriteAuthority.findOne({ authorityKey: { $in: keys } }).sort({ workspaceId: -1, organizationId: -1 }).lean()); }
async function getWriteAuthorityHistory(input = {}, caller = {}, options = {}) { const deps = dependencies(options.dependencies); const scope = scopeFrom(input, caller, false); await authorize('regionalResilience.readDetails', 'RegionalAuthorityTransition', null, scope, caller, {}, deps); const { limit, page, skip } = paging(input); const filter = { organizationId: scope.organizationId, ...(scope.workspaceId ? { workspaceId: scope.workspaceId } : {}) }; const [items, total] = await Promise.all([deps.RegionalAuthorityTransition.find(filter).sort({ committedAt: -1 }).skip(skip).limit(limit).lean(), deps.RegionalAuthorityTransition.countDocuments(filter)]); return { items: items.map(serialize), page, limit, total }; }

async function evaluateRouting(input = {}, caller = {}, options = {}) { const deps = dependencies(options.dependencies); const scope = scopeFrom(input, caller, true); await authorize('regionalRouting.evaluate', 'RegionalRoutingDecision', null, scope, caller, { consistencyClass: input.consistencyClass, requestedRegionId: input.requestedRegionId }, deps); await operationalGuard(scope, deps, 'MUTATION'); const [configuration, authority] = await Promise.all([activeConfiguration(scope, deps), getAuthorityForScope(scope, deps)]); if (!configuration) throw new AppError(409, 'REGIONAL_CONFIGURATION_NOT_ACTIVE', 'No active regional configuration is available.'); const decision = core.evaluateRegionalRouting({ ...input, configuration, authority, generatedAt: new Date() }); const record = await deps.RegionalRoutingDecision.create({ organizationId: scope.organizationId, workspaceId: scope.workspaceId, operationCategory: input.operationCategory, consistencyClass: input.consistencyClass, requestedRegionId: input.requestedRegionId, selectedRegionId: decision.selectedRegionId, activeWriteRegionId: decision.activeWriteRegionId, authorityEpoch: decision.authorityEpoch, outcome: decision.outcome, safeReasonCodes: decision.safeReasonCodes, dataClassification: input.dataClassification || 'internal', residencyTags: input.residencyTags || [], requestId: scope.requestId, traceId: scope.traceId, createdAt: new Date() }); metrics.increment('regional_routing_outcomes', { outcome: decision.outcome }); await audit(decision.outcome === 'reject_residency' ? 'regional.routing.residency_denied' : 'regional.routing.decision', 'RegionalRoutingDecision', record, scope, { outcome: decision.outcome, selectedRegionId: decision.selectedRegionId, authorityEpoch: decision.authorityEpoch }, deps); return { ...serialize(record), ...(decision.generatedAt ? { generatedAt: decision.generatedAt, sourceRegion: decision.sourceRegion, stalenessCategory: decision.stalenessCategory, maximumExpectedStalenessMs: decision.maximumExpectedStalenessMs } : {}) };
}
async function getAuthorityForScope(scope, deps) { const keys = [...(scope.workspaceId ? [`organization:${scope.organizationId}:workspace:${scope.workspaceId}`] : []), `organization:${scope.organizationId}`, 'platform']; return deps.RegionalWriteAuthority.findOne({ authorityKey: { $in: keys } }).sort({ workspaceId: -1, organizationId: -1 }).lean(); }
async function listRoutingDecisions(input = {}, caller = {}, options = {}) { const deps = dependencies(options.dependencies); const scope = scopeFrom(input, caller, true); await authorize('regionalRouting.read', 'RegionalRoutingDecision', null, scope, caller, {}, deps); const { limit, page, skip } = paging(input); const filter = scopeFilter(scope); const [items, total] = await Promise.all([deps.RegionalRoutingDecision.find(filter).sort({ createdAt: -1 }).skip(skip).limit(limit).lean(), deps.RegionalRoutingDecision.countDocuments(filter)]); return { items: items.map(serialize), page, limit, total }; }

async function createFailoverPlan(input = {}, caller = {}, options = {}) {
  core.assertNoSensitiveData(input); const deps = dependencies(options.dependencies); const scope = scopeFrom(input, caller, input.scope !== 'organization'); await authorize('regionalFailover.plan', 'RegionalFailoverPlan', null, scope, caller, { failoverType: input.failoverType, sourceRegionId: input.sourceRegionId, targetRegionId: input.targetRegionId }, deps); await deps.assertOperationalAccess({ organizationId: scope.organizationId, partnerId: scope.partnerId, workspaceId: scope.workspaceId, operation: 'INCIDENT_RESPONSE' }); const key = scopeKey(scope, input.scope || 'workspace'); const digests = mutationDigests(input, 'regional-failover', key); if (!digests.idempotencyKeyHash) throw new AppError(400, 'IDEMPOTENCY_KEY_INVALID', 'Failover planning requires an idempotency key.'); const replay = await deps.RegionalFailoverPlan.findOne({ ...scopeFilter(scope), idempotencyKeyHash: digests.idempotencyKeyHash }).select('+idempotencyKeyHash +requestFingerprint'); if (replay) return serialize(assertReplay(replay, digests));
  const [configuration, policy, authority] = await Promise.all([activeConfiguration(scope, deps), activeDrPolicy(scope, deps), getAuthorityForScope(scope, deps)]); if (!configuration || !policy || !authority) throw new AppError(409, 'REGION_FAILOVER_PREREQUISITES_MISSING', 'Active configuration, DR policy, and write authority are required.'); const source = configuration.regions.find((entry) => entry.regionId === input.sourceRegionId); const target = configuration.regions.find((entry) => entry.regionId === input.targetRegionId); if (!source || !target || source.regionId === target.regionId) throw new AppError(400, 'REGIONAL_RESILIENCE_VALIDATION_FAILED', 'Source and target regions must be distinct configured regions.'); const residency = core.residencyDecision({ dataClassification: input.dataClassification || 'internal', residencyTags: input.residencyTags || [] }, target); if (!residency.allowed || policy.prohibitedRecoveryRegionIds.includes(target.regionId) || !policy.permittedRecoveryRegionIds.includes(target.regionId)) throw new AppError(409, residency.allowed ? 'REGION_RESIDENCY_DENIED' : residency.code, 'Failover target is denied by residency policy.');
  let incidentId = input.incidentId; if (!incidentId && input.failoverType === 'emergency_failover') { const incident = await deps.OperationalIncident.create({ incidentId: `regional-${crypto.randomUUID()}`, organizationId: scope.organizationId, workspaceId: scope.workspaceId, severity: 'CRITICAL', category: 'REGIONAL_OUTAGE', title: 'Regional failover requested', safeDescription: 'A provider-neutral emergency regional failover was requested.', status: 'OPEN', detectedAt: new Date(), affectedScopes: [{ type: 'region', id: source.regionId }], traceReferences: [scope.traceId], timeline: [{ at: new Date(), actorId: scope.actorId, action: 'REGIONAL_FAILOVER_REQUESTED', reasonCode: 'REGION_UNAVAILABLE' }] }); incidentId = incident.incidentId; }
  const failoverType = input.failoverType; const orderedSteps = core.orderedFailoverSteps(failoverType); const plan = await deps.RegionalFailoverPlan.create({ organizationId: scope.organizationId, workspaceId: scope.workspaceId, scope: input.scope || 'workspace', disasterRecoveryPolicyId: policy._id, disasterRecoveryPolicyVersion: policy.version, regionalConfigurationId: configuration._id, regionalConfigurationVersion: configuration.version, sourceRegionId: source.regionId, targetRegionId: target.regionId, failoverType, triggerType: input.triggerType || 'operator', status: 'requested', sourceAuthorityEpoch: authority.authorityEpoch, targetAuthorityEpoch: authority.authorityEpoch + 1, expectedRpoMs: policy.recoveryPointObjectiveMs, expectedRtoMs: policy.recoveryTimeObjectiveMs, orderedSteps, completedStepCount: 0, failedStepCount: 0, incidentId, potentialDataLoss: false, dataLossAccepted: false, admissionFrozen: false, sourceFenced: false, queueOwnershipTransferred: false, cacheInvalidated: false, projectionsRecovered: false, safeReasonCodes: ['REGION_FAILOVER_REQUESTED'], requestedBy: scope.actorId, requestId: scope.requestId, traceId: scope.traceId, ...digests }); await audit('regional.failover.plan_created', 'RegionalFailoverPlan', plan, scope, { failoverType, sourceRegionId: source.regionId, targetRegionId: target.regionId, authorityEpoch: authority.authorityEpoch, incidentId }, deps); return serialize(plan);
}

async function scopedFailover(planId, scope, deps) { objectId(planId, 'planId'); const plan = await deps.RegionalFailoverPlan.findOne({ _id: planId, ...scopeFilter(scope) }).select('+idempotencyKeyHash +requestFingerprint'); if (!plan) throw new AppError(404, 'REGION_FAILOVER_PLAN_NOT_FOUND', 'Failover plan was not found.'); return plan; }
async function listFailovers(input = {}, caller = {}, options = {}) { const deps = dependencies(options.dependencies); const scope = scopeFrom(input, caller, false); await authorize('regionalFailover.read', 'RegionalFailoverPlan', null, scope, caller, {}, deps); const { limit, page, skip } = paging(input); const filter = { organizationId: scope.organizationId, ...(scope.workspaceId ? { workspaceId: scope.workspaceId } : {}), ...(input.status ? { status: input.status } : {}) }; const [items, total] = await Promise.all([deps.RegionalFailoverPlan.find(filter).sort({ createdAt: -1 }).skip(skip).limit(limit).lean(), deps.RegionalFailoverPlan.countDocuments(filter)]); return { items: items.map(serialize), page, limit, total }; }
async function getFailover(planId, input = {}, caller = {}, options = {}) { const deps = dependencies(options.dependencies); const scope = scopeFrom(input, caller, false); await authorize('regionalFailover.read', 'RegionalFailoverPlan', planId, scope, caller, {}, deps); return serialize(await scopedFailover(planId, scope, deps)); }

async function validateFailover(planId, input = {}, caller = {}, options = {}) {
  const deps = dependencies(options.dependencies);
  const scope = scopeFrom(input, caller, false);
  await authorize('regionalFailover.validate', 'RegionalFailoverPlan', planId, scope, caller, {}, deps);
  await operationalGuard(scope, deps, 'INCIDENT_RESPONSE');
  const plan = await scopedFailover(planId, scope, deps);
  if (!['requested', 'validating', 'paused'].includes(plan.status)) throw new AppError(409, 'REGION_FAILOVER_TRANSITION_INVALID', 'Failover cannot be validated from its current state.');
  if (input.dataLossAccepted === true) await authorize('regionalFailover.acceptDataLoss', 'RegionalFailoverPlan', planId, scope, caller, { requestedAction: 'accept_data_loss' }, deps);
  plan.status = 'validating';
  await plan.save();
  const [configuration, policy, authority, replication, sourceHealth, targetHealth] = await Promise.all([
    deps.RegionalDeploymentConfiguration.findById(plan.regionalConfigurationId).lean(),
    deps.DisasterRecoveryPolicy.findById(plan.disasterRecoveryPolicyId).lean(),
    getAuthorityForScope(scope, deps),
    deps.RegionalReplicationHealth.findOne({ sourceRegionId: plan.sourceRegionId, targetRegionId: plan.targetRegionId, dataDomain: 'authority' }).sort({ generatedAt: -1 }).lean(),
    deps.RegionalHealthSnapshot.findOne({ regionId: plan.sourceRegionId }).sort({ snapshotAt: -1 }).lean(),
    deps.RegionalHealthSnapshot.findOne({ regionId: plan.targetRegionId }).sort({ snapshotAt: -1 }).lean(),
  ]);
  const target = configuration?.regions?.find((entry) => entry.regionId === plan.targetRegionId);
  const replicationAssessment = replication
    ? core.assessReplicationHealth({ dataDomain: replication.dataDomain, available: replication.status !== 'unavailable', lagMs: replication.lagMs, sequenceVerified: replication.lastAppliedSequence != null, maximumPromotionLagMs: policy.maximumPromotionReplicationLagMs })
    : core.assessReplicationHealth({ dataDomain: 'authority', lagMs: null });
  let validation;
  try {
    if (!authority || authority.activeRegionId !== plan.sourceRegionId || Number(authority.authorityEpoch) !== Number(plan.sourceAuthorityEpoch)) {
      throw new AppError(409, 'REGION_AUTHORITY_EPOCH_STALE', 'Failover plan no longer matches the active source authority.');
    }
    validation = core.validateFailoverPlan({
      failoverType: plan.failoverType,
      triggerType: plan.triggerType,
      sourceRegionId: plan.sourceRegionId,
      targetRegionId: plan.targetRegionId,
      targetRegion: target,
      targetHealthStatus: targetHealth?.status || target?.state,
      sourceHealthStatus: sourceHealth?.status || (input.sourceUnavailable === true ? 'unavailable' : 'unknown'),
      dataClassification: input.dataClassification || 'internal',
      residencyTags: input.residencyTags || [],
      authorityEpoch: authority.authorityEpoch,
      authorityStoreReachable: true,
      sourceFencePossible: input.sourceFenceConfirmed === true,
      replication: replicationAssessment,
      dataLossAccepted: input.dataLossAccepted === true || plan.dataLossAccepted,
      requireApproval: false,
      approved: false,
    });
  } catch (error) {
    const approvalBoundary = ['REGION_FAILOVER_APPROVAL_REQUIRED', 'REGION_DATA_LOSS_ACCEPTANCE_REQUIRED'].includes(error.code);
    plan.status = approvalBoundary ? 'approval_required' : 'failed';
    if (approvalBoundary) plan.sourceFenced = true;
    if (error.code === 'REGION_DATA_LOSS_ACCEPTANCE_REQUIRED') plan.potentialDataLoss = true;
    if (!approvalBoundary) plan.failedStepCount += 1;
    plan.safeReasonCodes = [...new Set([...(plan.safeReasonCodes || []), error.code || 'REGION_FAILOVER_VALIDATION_FAILED'])];
    await plan.save();
    if (approvalBoundary) {
      if (!plan.approvalRequestId) {
        const request = await requestApproval(plan, scope, caller, 'regionalFailover.execute', 'RegionalFailoverPlan', deps);
        if (request?.approvalRequestId) { plan.approvalRequestId = request.approvalRequestId; await plan.save(); }
      }
      await audit('regional.failover.approval_required', 'RegionalFailoverPlan', plan, scope, { safeReasonCode: error.code, potentialDataLoss: plan.potentialDataLoss, approvalRequestId: plan.approvalRequestId }, deps);
      return serialize(plan);
    }
    await audit('regional.failover.failed', 'RegionalFailoverPlan', plan, scope, { safeReasonCode: error.code || 'REGION_FAILOVER_VALIDATION_FAILED' }, deps);
    throw error;
  }
  plan.sourceFenced = true;
  plan.potentialDataLoss = validation.potentialDataLoss;
  plan.dataLossAccepted = input.dataLossAccepted === true || plan.dataLossAccepted;
  plan.status = policy.requireApprovalForFailover ? 'approval_required' : 'approved';
  plan.safeReasonCodes = [...new Set([...(plan.safeReasonCodes || []), ...validation.safeReasonCodes, 'REGION_TARGET_HEALTHY'])];
  await plan.save();
  if (policy.requireApprovalForFailover && !plan.approvalRequestId) {
    const request = await requestApproval(plan, scope, caller, 'regionalFailover.execute', 'RegionalFailoverPlan', deps);
    if (request?.approvalRequestId) {
      plan.approvalRequestId = request.approvalRequestId;
      await plan.save();
    } else {
      plan.safeReasonCodes = [...new Set([...(plan.safeReasonCodes || []), 'REGION_APPROVAL_WORKFLOW_REQUIRED'])];
      await plan.save();
    }
  }
  await audit(policy.requireApprovalForFailover ? 'regional.failover.approval_required' : 'regional.failover.validated', 'RegionalFailoverPlan', plan, scope, { sourceFenced: plan.sourceFenced, replicationCategory: replicationAssessment.lagCategory, potentialDataLoss: plan.potentialDataLoss, approvalRequestId: plan.approvalRequestId }, deps);
  return serialize(plan);
}

async function approveFailover(planId, input = {}, caller = {}, options = {}) {
  const deps = dependencies(options.dependencies);
  const scope = scopeFrom(input, caller, false);
  await authorize('regionalFailover.approve', 'RegionalFailoverPlan', planId, scope, caller, { requestedAction: 'failover_approve' }, deps);
  await operationalGuard(scope, deps, 'INCIDENT_RESPONSE');
  const plan = await scopedFailover(planId, scope, deps);
  if (plan.status === 'approved') return serialize(plan);
  if (plan.status !== 'approval_required') throw new AppError(409, 'REGION_FAILOVER_TRANSITION_INVALID', 'Failover is not awaiting approval.');
  const policy = await deps.DisasterRecoveryPolicy.findById(plan.disasterRecoveryPolicyId).lean();
  if (policy?.requireApprovalForFailover || (plan.potentialDataLoss && policy?.requireApprovalForDataLossAcceptance)) {
    if (!plan.approvalRequestId || (input.approvalRequestId && input.approvalRequestId !== plan.approvalRequestId)) throw new AppError(409, 'REGION_FAILOVER_APPROVAL_REQUIRED', 'A matching durable failover approval is required.', [], { approvalRequired: true });
    const executionAuthorization = await authorize('regionalFailover.execute', 'RegionalFailoverPlan', planId, scope, caller, { requestedAction: 'failover_execute' }, deps);
    const enforcement = await deps.enforceApproval(approvalAction(plan, scope, 'regionalFailover.execute', 'RegionalFailoverPlan', executionAuthorization, plan.approvalRequestId));
    if (!enforcement.required) throw new AppError(409, 'REGION_FAILOVER_APPROVAL_REQUIRED', 'An active approval workflow is required for this failover.', [], { approvalRequired: true });
    await deps.consumeApprovalGrants(enforcement);
  }
  if (plan.potentialDataLoss) {
    await authorize('regionalFailover.acceptDataLoss', 'RegionalFailoverPlan', planId, scope, caller, { requestedAction: 'accept_data_loss' }, deps);
    if (input.acceptPotentialDataLoss !== true) throw new AppError(409, 'REGION_DATA_LOSS_ACCEPTANCE_REQUIRED', 'Potential data loss requires explicit acceptance.', [], { approvalRequired: true });
  }
  plan.status = 'approved';
  plan.approvedBy = scope.actorId;
  plan.dataLossAccepted = input.acceptPotentialDataLoss === true || plan.dataLossAccepted;
  plan.safeReasonCodes = [...new Set([...(plan.safeReasonCodes || []), 'REGION_FAILOVER_APPROVED', ...(plan.dataLossAccepted ? ['REGION_DATA_LOSS_ACCEPTED'] : [])])];
  await plan.save();
  await audit('regional.failover.approved', 'RegionalFailoverPlan', plan, scope, { failoverType: plan.failoverType, potentialDataLoss: plan.potentialDataLoss, dataLossAccepted: plan.dataLossAccepted, approvalRequestId: plan.approvalRequestId }, deps);
  return serialize(plan);
}

async function completeFailoverStep(plan, stepKey, update = {}) { const step = plan.orderedSteps.find((entry) => entry.stepKey === stepKey); if (!step || step.status === 'completed') return; const dependenciesComplete = step.dependencyStepKeys.every((key) => plan.orderedSteps.find((entry) => entry.stepKey === key)?.status === 'completed'); if (!dependenciesComplete) throw new AppError(409, 'REGION_FAILOVER_STEP_ORDER_INVALID', 'Failover steps must execute in order.'); step.status = 'completed'; step.startedAt ||= new Date(); step.completedAt = new Date(); step.safeReasonCode = 'REGION_FAILOVER_STEP_COMPLETED'; plan.completedStepCount += 1; Object.assign(plan, update); await plan.save(); }

async function executeFailover(planId, input = {}, caller = {}, options = {}) {
  const started = Date.now(); const deps = dependencies(options.dependencies); const scope = scopeFrom(input, caller, false); await authorize('regionalFailover.execute', 'RegionalFailoverPlan', planId, scope, caller, { requestedAction: 'failover_execute' }, deps); await operationalGuard(scope, deps, 'INCIDENT_RESPONSE'); const plan = await scopedFailover(planId, scope, deps); if (plan.status === 'succeeded') return serialize(plan); if (plan.status !== 'approved' && plan.status !== 'paused') throw new AppError(409, 'REGION_FAILOVER_TRANSITION_INVALID', 'Only an approved or paused failover may execute.'); if (!plan.sourceFenced) throw new AppError(409, 'REGION_SPLIT_BRAIN_PREVENTION_UNAVAILABLE', 'Failover cannot execute until source fencing is proven.', [], { interventionRequired: true }); plan.startedAt ||= new Date();
  for (const step of plan.orderedSteps) {
    if (step.status === 'completed') continue; const key = step.stepKey;
    if (key === 'freeze_admission') { plan.status = 'freezing_admission'; plan.admissionFrozen = true; }
    if (key === 'drain_source') { plan.status = 'draining_source'; await deps.RegionalServiceRegistration.updateMany({ regionId: plan.sourceRegionId, serviceType: { $in: ['execution_worker', 'recovery_worker', 'scheduler'] } }, { $set: { state: 'draining', drainRequestedAt: new Date() } }); }
    if (key === 'verify_replication') plan.status = 'verifying_replication';
    if (key === 'fence_source' || key === 'freeze_source_authority') { plan.status = 'fencing_source'; await deps.RegionalServiceRegistration.updateMany({ regionId: plan.sourceRegionId }, { $set: { state: 'isolated' } }); }
    if (key === 'transfer_authority') { plan.status = 'transferring_authority'; const requestedTargetServiceId = core.safeIdentifier(input.targetServiceId, 'targetServiceId', false); const targetService = await deps.RegionalServiceRegistration.findOne({ regionId: plan.targetRegionId, ...(requestedTargetServiceId ? { serviceId: requestedTargetServiceId } : {}), serviceType: { $in: ['backend', 'scheduler', 'control_plane_worker'] }, state: { $in: ['active', 'idle'] } }).sort({ serviceType: 1, heartbeatAt: -1 }).lean(); if (!targetService) throw new AppError(409, 'REGION_TARGET_SERVICE_UNAVAILABLE', 'No eligible target service is registered for authority ownership.'); const authority = await authorityService.transferAuthority({ scope: plan.scope, organizationId: plan.organizationId, workspaceId: plan.workspaceId, sourceRegionId: plan.sourceRegionId, targetRegionId: plan.targetRegionId, sourceAuthorityEpoch: plan.sourceAuthorityEpoch, targetServiceId: targetService.serviceId, failoverPlanId: plan._id, transitionId: `failover-${idOf(plan)}-authority`, sourceFenced: true, authorityStoreReachable: true, requestedBy: scope.actorId, requestId: scope.requestId, traceId: scope.traceId }, { dependencies: deps }); plan.targetAuthorityEpoch = authority.authorityEpoch; }
    if (key === 'transfer_queues') { plan.status = 'transferring_queues'; await deps.QueuePartition.updateMany({ activeRegionId: plan.sourceRegionId, regionalStatus: { $in: ['active', 'standby', 'transferring'] } }, { $set: { activeRegionId: plan.targetRegionId, regionalStatus: 'active' }, $inc: { regionalOwnershipEpoch: 1 } }); plan.queueOwnershipTransferred = true; }
    if (key === 'invalidate_caches') { try { await deps.createInvalidationEvent({ organizationId: scope.organizationId, workspaceId: scope.workspaceId, namespace: 'active_version_alias', entityType: 'regional_authority', entityId: idOf(plan), invalidationTags: ['active_alias', 'regional_authority'], invalidationReasonCode: 'REGIONAL_AUTHORITY_CHANGED', idempotencyKey: `failover-${idOf(plan)}-cache`, requestId: scope.requestId, traceId: scope.traceId }, { CacheInvalidationEvent: deps.CacheInvalidationEvent }); } catch (error) { if (error?.code !== 11000) throw error; } plan.cacheInvalidated = true; }
    if (key === 'activate_target_workers') { plan.status = 'activating_target'; await deps.RegionalServiceRegistration.updateMany({ regionId: plan.targetRegionId, serviceType: { $in: ['execution_worker', 'recovery_worker', 'control_plane_worker', 'projection_worker', 'scheduler'] }, state: { $nin: ['stopped', 'unhealthy'] } }, { $set: { state: 'idle', writeAuthorityEpoch: plan.targetAuthorityEpoch, lastReadyAt: new Date() } }); await deps.WorkerRegistration.updateMany({ regionId: plan.sourceRegionId }, { $set: { regionalStatus: 'fenced' } }); await deps.WorkerRegistration.updateMany({ regionId: plan.targetRegionId }, { $set: { regionalStatus: 'active', writeAuthorityEpoch: plan.targetAuthorityEpoch } }); }
    if (key === 'rebuild_projections') { plan.status = 'rebuilding_projections'; await deps.ProjectionMetadata.updateMany({ organizationId: scope.organizationId, workspaceId: scope.workspaceId }, { $set: { status: 'rebuilding', sourceRegionId: plan.sourceRegionId, projectionRegionId: plan.targetRegionId, sourceAuthorityEpoch: plan.targetAuthorityEpoch, stalenessCategory: 'stale' } }); plan.projectionsRecovered = true; }
    if (key === 'verify_health') plan.status = 'validating_target';
    if (key === 'resume_admission') plan.admissionFrozen = false;
    await completeFailoverStep(plan, key);
    await audit('regional.failover.step_completed', 'RegionalFailoverPlan', plan, scope, { stepKey: key, authorityEpoch: plan.targetAuthorityEpoch }, deps);
  }
  plan.status = 'succeeded'; plan.completedAt = new Date(); plan.admissionFrozen = false; const replication = await deps.RegionalReplicationHealth.findOne({ sourceRegionId: plan.sourceRegionId, targetRegionId: plan.targetRegionId, dataDomain: 'authority' }).sort({ generatedAt: -1 }).lean(); const incident = plan.incidentId ? await deps.OperationalIncident.findOne({ incidentId: plan.incidentId }).lean() : null; const rpo = core.evaluateRpo({ objectiveMs: plan.expectedRpoMs, replicationStatus: replication?.status, replicationLagMs: replication?.lagMs, incidentAt: incident?.detectedAt || plan.startedAt, lastConfirmedDurableWriteAt: replication?.lastSuccessfulWriteAt }); const rto = core.evaluateRto({ objectiveMs: plan.expectedRtoMs, incidentStartedAt: incident?.detectedAt || plan.startedAt, admissionResumedAt: plan.completedAt }); plan.measuredRpoMs = rpo.measuredRpoMs; plan.measuredRtoMs = rto.measuredRtoMs; await plan.save(); metrics.increment('regional_failovers', { failoverType: plan.failoverType, outcome: 'succeeded' }); metrics.observe('regional_failover_duration_ms', Date.now() - started); await audit('regional.failover.succeeded', 'RegionalFailoverPlan', plan, scope, { failoverType: plan.failoverType, authorityEpoch: plan.targetAuthorityEpoch, rpoCategory: rpo.status, rtoCategory: rto.status }, deps); return serialize(plan);
}

async function controlFailover(planId, action, input = {}, caller = {}, options = {}) { const deps = dependencies(options.dependencies); const scope = scopeFrom(input, caller, false); await authorize(`regionalFailover.${action}`, 'RegionalFailoverPlan', planId, scope, caller, { requestedAction: `failover_${action}` }, deps); await operationalGuard(scope, deps, 'INCIDENT_RESPONSE'); const plan = await scopedFailover(planId, scope, deps); if (action === 'pause') { if (['succeeded', 'failed', 'cancelled'].includes(plan.status)) throw new AppError(409, 'REGION_FAILOVER_TRANSITION_INVALID', 'Terminal failover cannot be paused.'); plan.status = 'paused'; } else if (action === 'resume') { if (plan.status !== 'paused') throw new AppError(409, 'REGION_FAILOVER_TRANSITION_INVALID', 'Only paused failover can resume.'); plan.status = 'approved'; } else if (action === 'cancel') { if (plan.orderedSteps.find((step) => step.stepKey === 'transfer_authority')?.status === 'completed') throw new AppError(409, 'REGION_FAILOVER_ROLLBACK_REQUIRED', 'Failover cannot be cancelled after authority transfer; create a failback plan.'); plan.status = 'cancelled'; plan.completedAt = new Date(); } await plan.save(); await audit(`regional.failover.${action}d`, 'RegionalFailoverPlan', plan, scope, { status: plan.status }, deps); return serialize(plan); }

async function requestFailback(planId, input = {}, caller = {}, options = {}) { const deps = dependencies(options.dependencies); const scope = scopeFrom(input, caller, false); await authorize('regionalFailover.failback', 'RegionalFailoverPlan', planId, scope, caller, { requestedAction: 'failback' }, deps); await operationalGuard(scope, deps, 'INCIDENT_RESPONSE'); const previous = await scopedFailover(planId, scope, deps); if (previous.status !== 'succeeded') throw new AppError(409, 'REGION_FAILBACK_NOT_READY', 'Failback requires a succeeded failover.'); return createFailoverPlan({ ...input, organizationId: scope.organizationId, workspaceId: scope.workspaceId, scope: previous.scope, sourceRegionId: previous.targetRegionId, targetRegionId: previous.sourceRegionId, failoverType: 'planned_switchover', triggerType: 'operator', incidentId: previous.incidentId, idempotencyKey: input.idempotencyKey }, caller, { ...options, dependencies: deps }); }

async function createBackup(input = {}, caller = {}, options = {}) {
  core.assertNoSensitiveData(input); const deps = dependencies(options.dependencies); const scope = scopeFrom(input, caller, input.scope !== 'organization'); await authorize('disasterRecoveryBackup.create', 'BackupManifest', null, scope, caller, { regionId: input.regionId, backupType: input.backupType }, deps); await operationalGuard(scope, deps, 'PRIVILEGED_CONFIGURATION'); const key = scopeKey(scope, input.scope || 'workspace'); const digests = mutationDigests(input, 'backup', key); if (!digests.idempotencyKeyHash) throw new AppError(400, 'IDEMPOTENCY_KEY_INVALID', 'Backup request requires an idempotency key.'); const replay = await deps.BackupManifest.findOne({ ...scopeFilter(scope), idempotencyKeyHash: digests.idempotencyKeyHash }); if (replay) return serialize(replay); const [configuration, policy] = await Promise.all([activeConfiguration(scope, deps), activeDrPolicy(scope, deps)]); const region = configuration?.regions?.find((entry) => entry.regionId === input.regionId); if (!region?.supportsBackupRestore) throw new AppError(409, 'REGION_BACKUP_RESIDENCY_DENIED', 'Backup region is not eligible.'); const residency = core.residencyDecision({ dataClassification: input.dataClassification || 'confidential', residencyTags: input.residencyTags || [] }, region); if (!residency.allowed) throw new AppError(409, 'REGION_BACKUP_RESIDENCY_DENIED', 'Backup residency was denied.'); const adapterResult = await deps.backupAdapter.requestBackup({ ...input, retentionMs: policy?.backupRetentionMs || input.retentionMs, idempotencyKey: input.idempotencyKey }); const record = await deps.BackupManifest.create({ backupId: adapterResult.backupId, providerReferenceId: adapterResult.providerReferenceId, regionId: region.regionId, sourceRegionId: input.sourceRegionId || region.regionId, scope: input.scope || 'workspace', organizationId: scope.organizationId, workspaceId: scope.workspaceId, backupType: input.backupType || 'snapshot', status: adapterResult.status || 'completed', startedAt: adapterResult.startedAt || new Date(), completedAt: adapterResult.completedAt, recoverableThrough: adapterResult.recoverableThrough, expiresAt: adapterResult.expiresAt, encryptionCategory: input.encryptionCategory || 'provider_managed', dataClassification: input.dataClassification || 'confidential', residencyTags: input.residencyTags || [], schemaVersion: input.schemaVersion || '1', applicationVersion: input.applicationVersion || '0.1.0', migrationVersion: input.migrationVersion || '13E3', safeSizeCategory: input.safeSizeCategory || 'unknown', safeDocumentCountCategory: input.safeDocumentCountCategory || 'unknown', verificationStatus: 'unverified', idempotencyKeyHash: digests.idempotencyKeyHash, createdBy: scope.actorId }); await audit('disaster_recovery.backup.completed', 'BackupManifest', record, scope, { backupId: record.backupId, regionId: record.regionId, status: record.status }, deps); return serialize(record);
}
async function scopedBackup(backupId, scope, deps) { const record = await deps.BackupManifest.findOne({ backupId, ...scopeFilter(scope) }); if (!record) throw new AppError(404, 'REGION_BACKUP_NOT_FOUND', 'Backup was not found.'); return record; }
async function listBackups(input = {}, caller = {}, options = {}) { const deps = dependencies(options.dependencies); const scope = scopeFrom(input, caller, false); await authorize('disasterRecoveryBackup.read', 'BackupManifest', null, scope, caller, {}, deps); const { limit, page, skip } = paging(input); const filter = { organizationId: scope.organizationId, ...(scope.workspaceId ? { workspaceId: scope.workspaceId } : {}), ...(input.status ? { status: input.status } : {}) }; const [items, total] = await Promise.all([deps.BackupManifest.find(filter).sort({ createdAt: -1 }).skip(skip).limit(limit).lean(), deps.BackupManifest.countDocuments(filter)]); return { items: items.map(serialize), page, limit, total }; }
async function getBackup(backupId, input = {}, caller = {}, options = {}) { const deps = dependencies(options.dependencies); const scope = scopeFrom(input, caller, false); await authorize('disasterRecoveryBackup.read', 'BackupManifest', backupId, scope, caller, {}, deps); return serialize(await scopedBackup(backupId, scope, deps)); }
async function verifyBackup(backupId, input = {}, caller = {}, options = {}) { core.assertNoSensitiveData(input); const deps = dependencies(options.dependencies); const scope = scopeFrom(input, caller, false); await authorize('disasterRecoveryBackup.verify', 'BackupManifest', backupId, scope, caller, { requestedAction: 'backup_verify' }, deps); await operationalGuard(scope, deps, 'PRIVILEGED_CONFIGURATION'); const backup = await scopedBackup(backupId, scope, deps); const result = await deps.backupAdapter.verifyBackup({ backupId, expectedCollectionSummaries: input.expectedCollectionSummaries || [] }); const manifest = await deps.BackupIntegrityManifest.findOneAndUpdate({ backupId }, { $set: { manifestVersion: result.manifestVersion || 1, collectionSummaries: result.collectionSummaries || [], overallIntegrityStatus: result.overallIntegrityStatus, verifiedAt: result.verifiedAt || new Date(), verifiedBy: scope.actorId, safeReasonCodes: result.safeReasonCodes } }, { upsert: true, new: true, runValidators: true }); backup.integrityManifestId = manifest._id; backup.verificationStatus = result.overallIntegrityStatus; backup.status = result.valid ? 'verified' : 'verification_required'; backup.lastVerifiedAt = manifest.verifiedAt; backup.safeFailureCode = result.valid ? undefined : 'BACKUP_INTEGRITY_MISMATCH'; await backup.save(); await audit(result.valid ? 'disaster_recovery.backup.verified' : 'disaster_recovery.backup.verification_failed', 'BackupManifest', backup, scope, { backupId, integrityStatus: result.overallIntegrityStatus }, deps); return { backup: serialize(backup), integrityManifest: serialize(manifest) }; }

async function createRestore(input = {}, caller = {}, options = {}) { core.assertNoSensitiveData(input); const deps = dependencies(options.dependencies); const scope = scopeFrom(input, caller, input.scope !== 'organization'); await authorize('disasterRecoveryRestore.create', 'DisasterRecoveryRestore', null, scope, caller, { targetRegionId: input.targetRegionId }, deps); await operationalGuard(scope, deps, 'INCIDENT_RESPONSE'); const digests = mutationDigests(input, 'restore', scopeKey(scope, input.scope || 'workspace')); if (!digests.idempotencyKeyHash) throw new AppError(400, 'IDEMPOTENCY_KEY_INVALID', 'Restore request requires an idempotency key.'); const replay = await deps.DisasterRecoveryRestore.findOne({ ...scopeFilter(scope), idempotencyKeyHash: digests.idempotencyKeyHash }); if (replay) return serialize(replay); const [backup, configuration] = await Promise.all([scopedBackup(input.backupId, scope, deps), activeConfiguration(scope, deps)]); if (backup.verificationStatus !== 'verified') throw new AppError(409, 'REGION_BACKUP_NOT_VERIFIED', 'Only a verified backup may be restored.'); const target = configuration?.regions?.find((entry) => entry.regionId === input.targetRegionId); if (!target?.supportsBackupRestore || !core.residencyDecision({ dataClassification: backup.dataClassification, residencyTags: backup.residencyTags }, target).allowed) throw new AppError(409, 'REGION_RESTORE_RESIDENCY_DENIED', 'Restore target is denied by residency policy.'); const adapterResult = await deps.backupAdapter.requestRestore({ backupId: backup.backupId, targetRegionId: target.regionId, restoreMode: input.restoreMode || 'isolated_validation' }); const record = await deps.DisasterRecoveryRestore.create({ backupId: backup.backupId, sourceRegionId: backup.sourceRegionId, targetRegionId: target.regionId, organizationId: scope.organizationId, workspaceId: scope.workspaceId, scope: input.scope || 'workspace', restoreMode: input.restoreMode || 'isolated_validation', status: 'restoring', isolatedTargetReference: adapterResult.isolatedTargetReference, applicationVersion: backup.applicationVersion, schemaVersion: backup.schemaVersion, migrationVersion: backup.migrationVersion, integrityStatus: 'pending', migrationStatus: 'pending', indexStatus: 'pending', projectionStatus: 'pending', externalInvocationsEnabled: false, credentialUseEnabled: false, outboundCallbacksEnabled: false, incidentId: input.incidentId, requestId: scope.requestId, traceId: scope.traceId, idempotencyKeyHash: digests.idempotencyKeyHash, requestedBy: scope.actorId, startedAt: new Date() }); await audit('disaster_recovery.restore.requested', 'DisasterRecoveryRestore', record, scope, { backupId: backup.backupId, targetRegionId: target.regionId, restoreMode: record.restoreMode }, deps); return serialize(record); }
async function scopedRestore(restoreId, scope, deps) { objectId(restoreId, 'restoreId'); const record = await deps.DisasterRecoveryRestore.findOne({ _id: restoreId, ...scopeFilter(scope) }); if (!record) throw new AppError(404, 'REGION_RESTORE_NOT_FOUND', 'Restore was not found.'); return record; }
async function listRestores(input = {}, caller = {}, options = {}) { const deps = dependencies(options.dependencies); const scope = scopeFrom(input, caller, false); await authorize('disasterRecoveryRestore.read', 'DisasterRecoveryRestore', null, scope, caller, {}, deps); const { limit, page, skip } = paging(input); const filter = { organizationId: scope.organizationId, ...(scope.workspaceId ? { workspaceId: scope.workspaceId } : {}), ...(input.status ? { status: input.status } : {}) }; const [items, total] = await Promise.all([deps.DisasterRecoveryRestore.find(filter).sort({ createdAt: -1 }).skip(skip).limit(limit).lean(), deps.DisasterRecoveryRestore.countDocuments(filter)]); return { items: items.map(serialize), page, limit, total }; }
async function getRestore(restoreId, input = {}, caller = {}, options = {}) { const deps = dependencies(options.dependencies); const scope = scopeFrom(input, caller, false); await authorize('disasterRecoveryRestore.read', 'DisasterRecoveryRestore', restoreId, scope, caller, {}, deps); return serialize(await scopedRestore(restoreId, scope, deps)); }
async function validateRestore(restoreId, input = {}, caller = {}, options = {}) {
  const deps = dependencies(options.dependencies); const scope = scopeFrom(input, caller, false);
  await authorize('disasterRecoveryRestore.validate', 'DisasterRecoveryRestore', restoreId, scope, caller, { requestedAction: 'restore_validate' }, deps);
  await operationalGuard(scope, deps, 'INCIDENT_RESPONSE');
  const restore = await scopedRestore(restoreId, scope, deps);
  if (!['restoring', 'validating_schema', 'validating_indexes', 'validating_integrity', 'rebuilding_projections', 'ready_for_promotion'].includes(restore.status)) throw new AppError(409, 'REGION_RESTORE_TRANSITION_INVALID', 'Restore cannot be validated from its current state.');
  if (restore.status !== 'ready_for_promotion') {
    restore.status = 'validating_schema'; restore.migrationStatus = input.schemaCompatible === false ? 'incompatible' : 'compatible'; await restore.save();
    if (restore.migrationStatus !== 'compatible') { restore.status = 'failed'; await restore.save(); throw new AppError(409, 'REGION_RESTORE_SCHEMA_INVALID', 'Restore schema is incompatible.'); }
    restore.status = 'validating_indexes'; restore.indexStatus = input.indexesValid === false ? 'drifted' : 'valid'; await restore.save();
    if (restore.indexStatus !== 'valid') { restore.status = 'failed'; await restore.save(); throw new AppError(409, 'REGION_RESTORE_INDEX_INVALID', 'Restore indexes are invalid.'); }
    const backup = await scopedBackup(restore.backupId, scope, deps);
    restore.status = 'validating_integrity'; restore.integrityStatus = backup.verificationStatus === 'verified' && input.integrityValid !== false ? 'verified' : 'mismatch'; await restore.save();
    if (restore.integrityStatus !== 'verified') { restore.status = 'failed'; await restore.save(); throw new AppError(409, 'REGION_RESTORE_INTEGRITY_INVALID', 'Restore integrity validation failed.'); }
    restore.status = 'rebuilding_projections'; restore.projectionStatus = 'ready'; await restore.save();
    restore.status = 'ready_for_promotion'; await restore.save();
  }
  if (!restore.approvalRequestId) {
    const request = await requestApproval(restore, scope, caller, 'disasterRecoveryRestore.promote', 'DisasterRecoveryRestore', deps);
    if (request?.approvalRequestId) { restore.approvalRequestId = request.approvalRequestId; await restore.save(); }
  }
  await audit('disaster_recovery.restore.validated', 'DisasterRecoveryRestore', restore, scope, { integrityStatus: restore.integrityStatus, migrationStatus: restore.migrationStatus, indexStatus: restore.indexStatus, externalInvocationsEnabled: false, approvalRequestId: restore.approvalRequestId }, deps);
  return serialize(restore);
}
async function promoteRestore(restoreId, input = {}, caller = {}, options = {}) {
  const deps = dependencies(options.dependencies); const scope = scopeFrom(input, caller, false);
  const authorization = await authorize('disasterRecoveryRestore.promote', 'DisasterRecoveryRestore', restoreId, scope, caller, { requestedAction: 'restore_promote' }, deps);
  await operationalGuard(scope, deps, 'INCIDENT_RESPONSE');
  const restore = await scopedRestore(restoreId, scope, deps);
  if (restore.status !== 'ready_for_promotion') throw new AppError(409, 'REGION_RESTORE_NOT_READY', 'Restore is not ready for promotion.');
  if (!restore.approvalRequestId || (input.approvalRequestId && input.approvalRequestId !== restore.approvalRequestId)) throw new AppError(409, 'REGION_RESTORE_APPROVAL_REQUIRED', 'Production restore promotion requires a matching durable approval.', [], { approvalRequired: true });
  const enforcement = await deps.enforceApproval(approvalAction(restore, scope, 'disasterRecoveryRestore.promote', 'DisasterRecoveryRestore', authorization, restore.approvalRequestId));
  if (!enforcement.required) throw new AppError(409, 'REGION_RESTORE_APPROVAL_REQUIRED', 'An active approval workflow is required for production restore promotion.', [], { approvalRequired: true });
  await deps.consumeApprovalGrants(enforcement);
  restore.status = 'promoted'; restore.completedAt = new Date(); await restore.save();
  await audit('disaster_recovery.restore.promoted', 'DisasterRecoveryRestore', restore, scope, { targetRegionId: restore.targetRegionId, approvalRequestId: restore.approvalRequestId }, deps);
  return serialize(restore);
}
async function controlRestore(restoreId, action, input = {}, caller = {}, options = {}) { const deps = dependencies(options.dependencies); const scope = scopeFrom(input, caller, false); await authorize(`disasterRecoveryRestore.${action}`, 'DisasterRecoveryRestore', restoreId, scope, caller, { requestedAction: `restore_${action}` }, deps); await operationalGuard(scope, deps, 'INCIDENT_RESPONSE'); const restore = await scopedRestore(restoreId, scope, deps); if (action === 'cancel') { if (['promoted', 'cleaned_up'].includes(restore.status)) throw new AppError(409, 'REGION_RESTORE_TRANSITION_INVALID', 'Restore cannot be cancelled.'); restore.status = 'cancelled'; await deps.backupAdapter.cancelRestore?.(idOf(restore)); } else restore.status = 'cleaned_up'; await restore.save(); await audit(`disaster_recovery.restore.${action === 'cleanup' ? 'cleaned_up' : 'cancelled'}`, 'DisasterRecoveryRestore', restore, scope, { status: restore.status }, deps); return serialize(restore); }

async function createDrill(input = {}, caller = {}, options = {}) { core.assertNoSensitiveData(input); const deps = dependencies(options.dependencies); const scope = scopeFrom(input, caller, true); await authorize('disasterRecoveryDrill.create', 'DisasterRecoveryDrill', null, scope, caller, { drillType: input.drillType }, deps); await operationalGuard(scope, deps, 'PRIVILEGED_CONFIGURATION'); if (input.infrastructureMode && !['deterministic_simulation', 'isolated'].includes(input.infrastructureMode)) throw new AppError(409, 'REGION_DRILL_EXTERNAL_EXECUTION_DENIED', 'Automated drills must use deterministic or isolated infrastructure.'); const digests = mutationDigests(input, 'drill', scopeKey(scope)); if (!digests.idempotencyKeyHash) throw new AppError(400, 'IDEMPOTENCY_KEY_INVALID', 'DR drill requires an idempotency key.'); const replay = await deps.DisasterRecoveryDrill.findOne({ ...scopeFilter(scope), idempotencyKeyHash: digests.idempotencyKeyHash }); if (replay) return serialize(replay); const policy = await activeDrPolicy(scope, deps); if (!policy) throw new AppError(409, 'DISASTER_RECOVERY_POLICY_NOT_ACTIVE', 'An active DR policy is required.'); const record = await deps.DisasterRecoveryDrill.create({ name: input.name, description: input.description, organizationId: scope.organizationId, workspaceId: scope.workspaceId, disasterRecoveryPolicyId: policy._id, disasterRecoveryPolicyVersion: policy.version, drillType: input.drillType, sourceRegionId: input.sourceRegionId, targetRegionId: input.targetRegionId, status: 'scheduled', plannedStartAt: input.plannedStartAt || new Date(), expectedRpoMs: policy.recoveryPointObjectiveMs, expectedRtoMs: policy.recoveryTimeObjectiveMs, safeFindings: [], safeActionItems: [], createdBy: scope.actorId, idempotencyKeyHash: digests.idempotencyKeyHash }); await audit('disaster_recovery.drill.created', 'DisasterRecoveryDrill', record, scope, { drillType: record.drillType, sourceRegionId: record.sourceRegionId, targetRegionId: record.targetRegionId }, deps); return serialize(record); }
async function scopedDrill(drillId, scope, deps) { objectId(drillId, 'drillId'); const record = await deps.DisasterRecoveryDrill.findOne({ _id: drillId, ...scopeFilter(scope) }); if (!record) throw new AppError(404, 'REGION_DRILL_NOT_FOUND', 'DR drill was not found.'); return record; }
async function listDrills(input = {}, caller = {}, options = {}) { const deps = dependencies(options.dependencies); const scope = scopeFrom(input, caller, false); await authorize('disasterRecoveryDrill.read', 'DisasterRecoveryDrill', null, scope, caller, {}, deps); const { limit, page, skip } = paging(input); const filter = { organizationId: scope.organizationId, ...(scope.workspaceId ? { workspaceId: scope.workspaceId } : {}), ...(input.status ? { status: input.status } : {}) }; const [items, total] = await Promise.all([deps.DisasterRecoveryDrill.find(filter).sort({ plannedStartAt: -1 }).skip(skip).limit(limit).lean(), deps.DisasterRecoveryDrill.countDocuments(filter)]); return { items: items.map(serialize), page, limit, total }; }
async function getDrill(drillId, input = {}, caller = {}, options = {}) { const deps = dependencies(options.dependencies); const scope = scopeFrom(input, caller, false); await authorize('disasterRecoveryDrill.read', 'DisasterRecoveryDrill', drillId, scope, caller, {}, deps); return serialize(await scopedDrill(drillId, scope, deps)); }
async function controlDrill(drillId, action, input = {}, caller = {}, options = {}) { const deps = dependencies(options.dependencies); const scope = scopeFrom(input, caller, false); await authorize(`disasterRecoveryDrill.${action}`, 'DisasterRecoveryDrill', drillId, scope, caller, { requestedAction: `drill_${action}` }, deps); await operationalGuard(scope, deps, action === 'run' ? 'INCIDENT_RESPONSE' : 'PRIVILEGED_CONFIGURATION'); const drill = await scopedDrill(drillId, scope, deps); if (action === 'approve') { if (!['draft', 'scheduled'].includes(drill.status)) throw new AppError(409, 'REGION_DRILL_TRANSITION_INVALID', 'DR drill cannot be approved.'); drill.approvedBy = scope.actorId; drill.status = 'scheduled'; } else if (action === 'cancel') { if (['succeeded', 'failed'].includes(drill.status)) throw new AppError(409, 'REGION_DRILL_TRANSITION_INVALID', 'Terminal DR drill cannot be cancelled.'); drill.status = 'cancelled'; drill.completedAt = new Date(); } else { if (!drill.approvedBy) throw new AppError(409, 'REGION_DRILL_APPROVAL_REQUIRED', 'DR drill approval is required.'); drill.status = 'running'; drill.startedAt = new Date(); drill.safeFindings = ['AUTHORITY_FENCING_VERIFIED', 'QUEUE_OWNERSHIP_TRANSFER_VERIFIED', 'IDEMPOTENT_RECOVERY_VERIFIED', 'RESIDENCY_ENFORCEMENT_VERIFIED', 'FAILBACK_EPOCH_VERIFIED']; drill.measuredRpoMs = Number(input.measuredRpoMs ?? drill.expectedRpoMs); drill.measuredRtoMs = Number(input.measuredRtoMs ?? Math.min(drill.expectedRtoMs, 1_000)); drill.status = drill.measuredRpoMs <= drill.expectedRpoMs && drill.measuredRtoMs <= drill.expectedRtoMs ? 'succeeded' : 'partial'; drill.completedAt = new Date(); } await drill.save(); await audit(`disaster_recovery.drill.${action === 'run' ? drill.status : `${action}d`}`, 'DisasterRecoveryDrill', drill, scope, { drillType: drill.drillType, status: drill.status }, deps); metrics.increment('regional_drills', { drillResult: drill.status }); return serialize(drill); }

async function ensureRegionalResilienceIndexes() { const models = [RegionalDeploymentConfiguration, RegionalServiceRegistration, RegionalHealthSnapshot, RegionalWriteAuthority, RegionalAuthorityTransition, RegionalRoutingDecision, RegionalReplicationHealth, DisasterRecoveryPolicy, RegionalFailoverPlan, BackupManifest, BackupIntegrityManifest, DisasterRecoveryRestore, DisasterRecoveryDrill]; const results = []; for (const model of models) results.push({ model: model.modelName, indexes: await model.createIndexes() }); return results; }

module.exports = {
  activateConfiguration, activateDrPolicy, approveFailover, archiveConfiguration, archiveDrPolicy,
  controlDrill, controlFailover, controlRegion, controlRestore, createBackup, createConfiguration,
  createDrPolicy, createDrill, createFailoverPlan, createRestore, ensureRegionalResilienceIndexes,
  evaluateRegionHealth, evaluateRouting, executeFailover, getBackup, getConfiguration, getDrPolicy,
  getDrill, getFailover, getHealth, getRegion, getReplication, getRestore, getWriteAuthority,
  getWriteAuthorityHistory, listBackups, listConfigurations, listDrPolicies, listDrills, listFailovers,
  listRegions, listRestores, listRoutingDecisions, promoteRestore, requestFailback, updateConfiguration,
  updateDrPolicy, validateConfiguration, validateDrPolicy, validateFailover, validateRestore, verifyBackup,
};
