const express = require('express');
const controller = require('../controllers/regionalResilienceController');
const { authenticatePartner } = require('../middleware/authenticatePartner');
const { requiresPermission } = require('../middleware/requiresPermission');

const regionalResilienceRouter = express.Router();
regionalResilienceRouter.use(authenticatePartner);
function protect(method, path, permission, type, handler) { regionalResilienceRouter[method](path, requiresPermission(permission, { resourceType: type }), handler); }

protect('post', '/configurations', 'regionalConfiguration.create', 'RegionalDeploymentConfiguration', controller.createConfiguration);
protect('get', '/configurations', 'regionalConfiguration.read', 'RegionalDeploymentConfiguration', controller.listConfigurations);
protect('get', '/configurations/:configurationId', 'regionalConfiguration.read', 'RegionalDeploymentConfiguration', controller.getConfiguration);
protect('patch', '/configurations/:configurationId', 'regionalConfiguration.update', 'RegionalDeploymentConfiguration', controller.updateConfiguration);
protect('post', '/configurations/:configurationId/validate', 'regionalConfiguration.validate', 'RegionalDeploymentConfiguration', controller.validateConfiguration);
protect('post', '/configurations/:configurationId/activate', 'regionalConfiguration.activate', 'RegionalDeploymentConfiguration', controller.activateConfiguration);
protect('post', '/configurations/:configurationId/archive', 'regionalConfiguration.archive', 'RegionalDeploymentConfiguration', controller.archiveConfiguration);
protect('post', '/dr-policies', 'disasterRecoveryPolicy.create', 'DisasterRecoveryPolicy', controller.createDrPolicy);
protect('get', '/dr-policies', 'disasterRecoveryPolicy.read', 'DisasterRecoveryPolicy', controller.listDrPolicies);
protect('get', '/dr-policies/:policyId', 'disasterRecoveryPolicy.read', 'DisasterRecoveryPolicy', controller.getDrPolicy);
protect('patch', '/dr-policies/:policyId', 'disasterRecoveryPolicy.update', 'DisasterRecoveryPolicy', controller.updateDrPolicy);
protect('post', '/dr-policies/:policyId/validate', 'disasterRecoveryPolicy.validate', 'DisasterRecoveryPolicy', controller.validateDrPolicy);
protect('post', '/dr-policies/:policyId/activate', 'disasterRecoveryPolicy.activate', 'DisasterRecoveryPolicy', controller.activateDrPolicy);
protect('post', '/dr-policies/:policyId/archive', 'disasterRecoveryPolicy.archive', 'DisasterRecoveryPolicy', controller.archiveDrPolicy);
protect('get', '/regions', 'regionalResilience.read', 'RegionalDeploymentConfiguration', controller.listRegions);
protect('get', '/regions/:regionId', 'regionalResilience.readDetails', 'RegionalDeploymentConfiguration', controller.getRegion);
protect('post', '/regions/:regionId/isolate', 'regionalOperations.isolate', 'RegionalServiceRegistration', controller.isolateRegion);
protect('post', '/regions/:regionId/unisolate', 'regionalOperations.unisolate', 'RegionalServiceRegistration', controller.unisolateRegion);
protect('post', '/regions/:regionId/drain', 'regionalOperations.drain', 'RegionalServiceRegistration', controller.drainRegion);
protect('post', '/regions/:regionId/resume', 'regionalOperations.resume', 'RegionalServiceRegistration', controller.resumeRegion);
protect('post', '/regions/:regionId/freeze-writes', 'regionalOperations.freezeWrites', 'RegionalWriteAuthority', controller.freezeWrites);
protect('post', '/regions/:regionId/evaluate-health', 'regionalResilience.readHealth', 'RegionalHealthSnapshot', controller.evaluateHealth);
protect('get', '/write-authority', 'regionalResilience.readDetails', 'RegionalWriteAuthority', controller.getWriteAuthority);
protect('get', '/write-authority/history', 'regionalResilience.readDetails', 'RegionalAuthorityTransition', controller.getWriteAuthorityHistory);
protect('post', '/failovers/plan', 'regionalFailover.plan', 'RegionalFailoverPlan', controller.createFailover);
protect('get', '/failovers', 'regionalFailover.read', 'RegionalFailoverPlan', controller.listFailovers);
protect('get', '/failovers/:planId', 'regionalFailover.read', 'RegionalFailoverPlan', controller.getFailover);
protect('post', '/failovers/:planId/validate', 'regionalFailover.validate', 'RegionalFailoverPlan', controller.validateFailover);
protect('post', '/failovers/:planId/approve', 'regionalFailover.approve', 'RegionalFailoverPlan', controller.approveFailover);
protect('post', '/failovers/:planId/execute', 'regionalFailover.execute', 'RegionalFailoverPlan', controller.executeFailover);
protect('post', '/failovers/:planId/pause', 'regionalFailover.pause', 'RegionalFailoverPlan', controller.pauseFailover);
protect('post', '/failovers/:planId/resume', 'regionalFailover.resume', 'RegionalFailoverPlan', controller.resumeFailover);
protect('post', '/failovers/:planId/cancel', 'regionalFailover.cancel', 'RegionalFailoverPlan', controller.cancelFailover);
protect('post', '/failovers/:planId/failback', 'regionalFailover.failback', 'RegionalFailoverPlan', controller.failback);
protect('get', '/health', 'regionalResilience.readHealth', 'RegionalHealthSnapshot', controller.getHealth);
protect('get', '/replication', 'regionalResilience.readReplication', 'RegionalReplicationHealth', controller.getReplication);
protect('get', '/routing-decisions', 'regionalRouting.read', 'RegionalRoutingDecision', controller.listRoutingDecisions);
protect('post', '/routing/evaluate', 'regionalRouting.evaluate', 'RegionalRoutingDecision', controller.evaluateRouting);
protect('post', '/backups', 'disasterRecoveryBackup.create', 'BackupManifest', controller.createBackup);
protect('get', '/backups', 'disasterRecoveryBackup.read', 'BackupManifest', controller.listBackups);
protect('get', '/backups/:backupId', 'disasterRecoveryBackup.read', 'BackupManifest', controller.getBackup);
protect('post', '/backups/:backupId/verify', 'disasterRecoveryBackup.verify', 'BackupManifest', controller.verifyBackup);
protect('post', '/restores', 'disasterRecoveryRestore.create', 'DisasterRecoveryRestore', controller.createRestore);
protect('get', '/restores', 'disasterRecoveryRestore.read', 'DisasterRecoveryRestore', controller.listRestores);
protect('get', '/restores/:restoreId', 'disasterRecoveryRestore.read', 'DisasterRecoveryRestore', controller.getRestore);
protect('post', '/restores/:restoreId/validate', 'disasterRecoveryRestore.validate', 'DisasterRecoveryRestore', controller.validateRestore);
protect('post', '/restores/:restoreId/promote', 'disasterRecoveryRestore.promote', 'DisasterRecoveryRestore', controller.promoteRestore);
protect('post', '/restores/:restoreId/cancel', 'disasterRecoveryRestore.cancel', 'DisasterRecoveryRestore', controller.cancelRestore);
protect('post', '/restores/:restoreId/cleanup', 'disasterRecoveryRestore.cleanup', 'DisasterRecoveryRestore', controller.cleanupRestore);
protect('post', '/drills', 'disasterRecoveryDrill.create', 'DisasterRecoveryDrill', controller.createDrill);
protect('get', '/drills', 'disasterRecoveryDrill.read', 'DisasterRecoveryDrill', controller.listDrills);
protect('get', '/drills/:drillId', 'disasterRecoveryDrill.read', 'DisasterRecoveryDrill', controller.getDrill);
protect('post', '/drills/:drillId/approve', 'disasterRecoveryDrill.approve', 'DisasterRecoveryDrill', controller.approveDrill);
protect('post', '/drills/:drillId/run', 'disasterRecoveryDrill.run', 'DisasterRecoveryDrill', controller.runDrill);
protect('post', '/drills/:drillId/cancel', 'disasterRecoveryDrill.cancel', 'DisasterRecoveryDrill', controller.cancelDrill);
module.exports = { regionalResilienceRouter };
