import { Pause, Play, RefreshCw, RotateCcw } from 'lucide-react';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { apiClient } from '../api/apiClient.js';
import { useAppState } from '../app/AppState.jsx';
import { DataPerformanceNav } from '../components/DataPerformanceNav.jsx';
import { ErrorAlert, LoadingBlock } from '../components/Feedback.jsx';
import { StatusBadge } from '../components/StatusBadge.jsx';
import { PageHeader, Panel, SecondaryButton } from './pageChrome.jsx';

export function DataProjections() {
  const { identity, partnerConfigured, recordEvent } = useAppState();
  const [state, setState] = useState({ loading: false, error: null, items: [] });
  const [busy, setBusy] = useState('');
  const query = useMemo(() => new URLSearchParams({ workspaceId: identity.receivingWorkspaceId }), [identity.receivingWorkspaceId]);
  const load = useCallback(async () => { if (!partnerConfigured) return; setState((current) => ({ ...current, loading: true, error: null })); try { const result = await apiClient.get(`/data-performance/projections?${query}`); setState({ loading: false, error: null, items: result.items || [] }); } catch (error) { setState((current) => ({ ...current, loading: false, error })); } }, [partnerConfigured, query]);
  useEffect(() => { void load(); }, [load]);
  async function action(item, name) { setBusy(`${item.projectionName}:${name}`); try { await apiClient.post(`/data-performance/projections/${item.projectionName}/${name}`, { workspaceId: identity.receivingWorkspaceId, reasonCode: `OPERATOR_${name.toUpperCase()}` }, { headers: { 'Idempotency-Key': crypto.randomUUID() } }); recordEvent(`Projection ${name} requested`, item.projectionName, 'success'); await load(); } catch (error) { setState((current) => ({ ...current, error })); } finally { setBusy(''); } }
  return <><PageHeader eyebrow="Operations / Data access" title="Projections" description="Rebuildable eventual read models with durable checkpoints, fenced leases, and visible staleness." actions={<SecondaryButton onClick={load}><RefreshCw className={`h-4 w-4 ${state.loading ? 'animate-spin' : ''}`} />Refresh</SecondaryButton>} /><DataPerformanceNav />{state.error ? <ErrorAlert error={state.error} title="Projection request failed" /> : null}{state.loading ? <LoadingBlock label="Loading projections" /> : null}<Panel className="overflow-hidden p-0"><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-xs"><thead className="bg-slate-50 uppercase text-slate-500"><tr><th className="px-4 py-3">Projection</th><th>Version</th><th>Status</th><th>Workspace</th><th>Source sequence</th><th>Lag</th><th>Last processed</th><th>Last rebuild</th><th>Safe failure</th><th>Actions</th></tr></thead><tbody className="divide-y divide-slate-200">{state.items.map((item) => <tr key={item.projectionName}><td className="px-4 py-3 font-medium">{item.projectionName}</td><td>v{item.projectionVersion}</td><td><StatusBadge status={item.status} /></td><td>{identity.receivingWorkspaceId}</td><td>{item.sourceSequence}</td><td>{item.lagCategory}</td><td>{item.lastProcessedAt ? new Date(item.lastProcessedAt).toLocaleString() : '-'}</td><td>{item.lastRebuildAt ? new Date(item.lastRebuildAt).toLocaleString() : '-'}</td><td>{item.safeFailureCode || '-'}</td><td><div className="flex gap-2">{item.status === 'paused' ? <button title="Resume" disabled={Boolean(busy)} onClick={() => action(item, 'resume')}><Play className="h-3.5 w-3.5 text-cyan-700" /></button> : <button title="Pause" disabled={Boolean(busy)} onClick={() => action(item, 'pause')}><Pause className="h-3.5 w-3.5 text-cyan-700" /></button>}<button title="Rebuild" disabled={Boolean(busy)} onClick={() => action(item, 'rebuild')}><RotateCcw className="h-3.5 w-3.5 text-cyan-700" /></button></div></td></tr>)}</tbody></table>{!state.items.length ? <p className="py-8 text-center text-sm text-slate-500">No projection checkpoint exists for this workspace.</p> : null}</div></Panel></>;
}
