import { Archive, CheckCircle2, Save, ShieldCheck } from 'lucide-react';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { apiClient } from '../api/apiClient.js';
import { useAppState } from '../app/AppState.jsx';
import { ErrorAlert, LoadingBlock } from '../components/Feedback.jsx';
import { JsonEditor } from '../components/JsonEditor.jsx';
import { StatusBadge } from '../components/StatusBadge.jsx';
import { formatDate, PageHeader, Panel, PrimaryButton, SecondaryButton } from './pageChrome.jsx';

const editable = (item) => Object.fromEntries(['name', 'description', 'sourceSelector', 'targetSelector', 'sourceCapability', 'sourceOperation', 'targetCapability', 'targetOperation', 'purpose', 'purposeCode', 'allowedInputSchema', 'allowedOutputSchema', 'sourceOutputMapping', 'targetInputMapping', 'downstreamOutputMapping', 'allowedInputFields', 'deniedInputFields', 'allowedOutputFields', 'deniedOutputFields', 'transformationRules', 'redactionRules', 'minimizationRules', 'allowedDataClassifications', 'maximumDataClassification', 'allowedRegions', 'residencyRequirements', 'maximumPayloadBytes', 'maximumArrayItems', 'maximumStringLength', 'maximumObjectDepth', 'allowAttachments', 'allowedAttachmentTypes', 'maximumAttachmentBytes', 'allowFurtherDelegation', 'maximumDelegationDepth', 'requireApproval', 'approvalConditions', 'retentionPolicy', 'validFrom', 'expiresAt'].map((key) => [key, item[key]]));

export function DataContractDetail() {
  const { contractId } = useParams(); const navigate = useNavigate(); const { identity, partnerConfigured, recordEvent } = useAppState();
  const [state, setState] = useState({ loading: true, error: null, item: null }); const [editor, setEditor] = useState('{}'); const [validation, setValidation] = useState(null); const [busy, setBusy] = useState('');
  const query = useMemo(() => new URLSearchParams({ workspaceId: identity.receivingWorkspaceId }), [identity.receivingWorkspaceId]);
  const load = useCallback(() => { if (!partnerConfigured) return; apiClient.get(`/inter-agent-contracts/${contractId}?${query}`).then((item) => { setState({ loading: false, error: null, item }); setEditor(JSON.stringify(editable(item), null, 2)); }).catch((error) => setState({ loading: false, error, item: null })); }, [contractId, partnerConfigured, query]); useEffect(() => load(), [load]);
  async function action(name) { setBusy(name); try { const result = await apiClient.post(`/inter-agent-contracts/${contractId}/${name}`, { workspaceId: identity.receivingWorkspaceId }); if (name === 'validate') setValidation(result); else { recordEvent(`Data contract ${name}`, `${state.item.name} v${state.item.version}`, 'success'); load(); } } catch (error) { setState((value) => ({ ...value, error })); } finally { setBusy(''); } }
  async function save() { setBusy('save'); try { const item = await apiClient.patch(`/inter-agent-contracts/${contractId}`, { ...JSON.parse(editor), workspaceId: identity.receivingWorkspaceId }); recordEvent('Data contract saved', `${item.name} v${item.version}`, 'success'); if (item.contractId !== contractId) navigate(`/data-contracts/${item.contractId}`); else load(); } catch (error) { setState((value) => ({ ...value, error })); } finally { setBusy(''); } }
  if (state.loading) return <LoadingBlock label="Loading data contract" />; const item = state.item;
  return <><PageHeader eyebrow="Data contract version" title={item?.name || 'Contract unavailable'} description={item ? `Version ${item.version} · ${item.purposeCode} · updated ${formatDate(item.updatedAt)}` : ''} actions={<Link className="text-sm font-medium text-cyan-800" to="/data-contracts">Back to contracts</Link>} />{state.error ? <ErrorAlert error={state.error} title="Contract action failed" /> : null}{item ? <div className="space-y-6"><Panel><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><StatusBadge tone={item.status === 'active' ? 'ready' : 'pending'}>{item.status}</StatusBadge><span className="text-sm">{item.sourceCapability} → {item.targetCapability}</span><span className="text-sm">ceiling {item.maximumDataClassification}</span></div><div className="flex gap-2"><SecondaryButton onClick={() => action('validate')} disabled={Boolean(busy)}><ShieldCheck className="h-4 w-4" /> Validate</SecondaryButton>{item.status === 'draft' ? <PrimaryButton onClick={() => action('activate')} disabled={Boolean(busy)}><CheckCircle2 className="h-4 w-4" /> Activate</PrimaryButton> : null}{item.status !== 'archived' ? <SecondaryButton onClick={() => action('archive')} disabled={Boolean(busy)}><Archive className="h-4 w-4" /> Archive</SecondaryButton> : null}</div></div></Panel>{validation ? <Panel className={validation.valid ? 'border-emerald-200 bg-emerald-50' : 'border-rose-200 bg-rose-50'}><p className="font-semibold">{validation.valid ? 'Contract is valid' : 'Validation failed'}</p><ul className="mt-3 text-sm">{(validation.errors || []).map((error, index) => <li key={`${error.path}_${index}`}><span className="font-mono text-xs">{error.code}</span> · {error.path}: {error.message}</li>)}</ul></Panel> : null}<Panel><div className="mb-4 flex items-center justify-between"><div><h2 className="font-semibold">Contract editor</h2><p className="text-xs text-slate-500">Saving an active version creates a new draft version.</p></div><SecondaryButton onClick={save} disabled={Boolean(busy) || item.status === 'archived'}><Save className="h-4 w-4" /> Save</SecondaryButton></div><JsonEditor label="Contract JSON" value={editor} onChange={setEditor} rows={34} /></Panel></div> : null}</>;
}
