import { useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { apiClient } from '../api/apiClient.js';
import { useAppState } from '../app/AppState.jsx';
import { ErrorAlert, LoadingBlock } from '../components/Feedback.jsx';
import { StatusBadge } from '../components/StatusBadge.jsx';
import { formatDate, PageHeader, Panel } from './pageChrome.jsx';

export function SelectionDecisionDetail() {
  const { decisionId } = useParams(); const { identity, partnerConfigured } = useAppState(); const [state, setState] = useState({ loading: true, error: null, item: null });
  const query = useMemo(() => new URLSearchParams({ workspaceId: identity.receivingWorkspaceId }), [identity.receivingWorkspaceId]);
  useEffect(() => { if (!partnerConfigured) return; apiClient.get(`/agent-selection/decisions/${decisionId}?${query}`).then((item) => setState({ loading: false, error: null, item })).catch((error) => setState({ loading: false, error, item: null })); }, [decisionId, partnerConfigured, query]);
  if (state.loading) return <LoadingBlock label="Loading selection decision" />; const item = state.item;
  return <><PageHeader eyebrow="Selection decision" title={item ? `${item.requestedCapability} / ${item.requestedOperation}` : 'Decision unavailable'} description={item ? `Trace ${item.traceId} · created ${formatDate(item.createdAt)}` : ''} actions={<Link to="/selection-decisions" className="text-sm font-medium text-cyan-800">Back to decisions</Link>} />{state.error ? <ErrorAlert error={state.error} title="Decision request failed" /> : null}{item ? <div className="grid gap-6 xl:grid-cols-2"><Panel><div className="flex justify-between"><h2 className="font-semibold">Selected candidate</h2><StatusBadge tone={item.decisionStatus === 'selected' ? 'ready' : 'pending'}>{item.decisionStatus}</StatusBadge></div>{item.selectedCandidate ? <dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><dt className="text-slate-500">Agent</dt><dd>{item.selectedCandidate.agentName || item.selectedCandidate.passportId}</dd><dt className="text-slate-500">Publisher</dt><dd>{item.selectedCandidate.publisherName || '-'}</dd><dt className="text-slate-500">Connection</dt><dd className="break-all font-mono text-xs">{item.selectedCandidate.connectionId}</dd><dt className="text-slate-500">Score</dt><dd>{item.selectedCandidate.score}</dd><dt className="text-slate-500">Trust</dt><dd>{item.selectedCandidate.trustTier}</dd><dt className="text-slate-500">Snapshot</dt><dd>{formatDate(item.healthSnapshotAt)}</dd></dl> : <p className="mt-4 text-sm text-slate-600">No eligible candidate was selected.</p>}<h3 className="mt-6 text-xs font-semibold uppercase text-slate-500">Safe reasons</h3><ul className="mt-2 space-y-1 font-mono text-xs">{item.reasons.map((reason) => <li key={reason}>{reason}</li>)}</ul></Panel><div className="space-y-6"><Panel><h2 className="font-semibold">Aggregated exclusions</h2><dl className="mt-4 grid grid-cols-2 gap-3 text-sm">{Object.entries(item.excluded || {}).map(([key, value]) => <><dt key={`${key}_key`} className="text-slate-500">{key}</dt><dd key={`${key}_value`}>{value}</dd></>)}</dl></Panel><Panel><h2 className="font-semibold">Fallback order</h2><ol className="mt-4 space-y-2 text-sm">{item.fallbackCandidates.length ? item.fallbackCandidates.map((candidate) => <li key={candidate.connectionId} className="flex justify-between border-b pb-2"><span>{candidate.agentName} · {candidate.trustTier}</span><span>{candidate.score}</span></li>) : <li>No recorded fallbacks.</li>}</ol></Panel><Panel><h2 className="font-semibold">Governance linkage</h2><p className="mt-3 text-sm">Policy version {item.selectionPolicyVersion}</p><p className="mt-1 break-all text-xs">Approval: {item.approvalRequestId || 'not required'}</p><p className="mt-1 break-all text-xs">Run: {item.orchestrationRunId || 'standalone decision'}</p></Panel></div></div> : null}</>;
}
