const APPROVAL_WORKFLOW_STATUSES = Object.freeze(['DRAFT', 'ACTIVE', 'RETIRED']);
const APPROVAL_REQUEST_STATUSES = Object.freeze([
  'DRAFT',
  'PENDING',
  'PARTIALLY_APPROVED',
  'APPROVED',
  'REJECTED',
  'EXPIRED',
  'CANCELLED',
  'INVALIDATED',
  'CONSUMED',
  'EXECUTION_FAILED',
  'RECOVERY_REQUIRED',
]);
const APPROVAL_GRANT_STATUSES = Object.freeze([
  'ACTIVE',
  'CONSUMED',
  'EXPIRED',
  'REVOKED',
  'INVALIDATED',
]);
const APPROVAL_DECISIONS = Object.freeze(['APPROVE', 'REJECT']);
const HUMAN_ACTOR_TYPES = Object.freeze(['user']);
const EVIDENCE_RETENTION_CLASSES = Object.freeze([
  'OPERATIONAL',
  'SECURITY',
  'APPROVAL',
  'SECRET_GOVERNANCE',
  'COMPLIANCE',
  'LEGAL_HOLD',
]);
const EVIDENCE_EXPORT_STATUSES = Object.freeze([
  'PENDING',
  'RUNNING',
  'FINALIZING',
  'COMPLETED',
  'FAILED',
  'CANCELLED',
  'RECOVERY_REQUIRED',
]);
const LEGAL_HOLD_STATUSES = Object.freeze(['DRAFT', 'ACTIVE', 'RELEASED', 'EXPIRED']);
const RETENTION_POLICY_STATUSES = Object.freeze(['DRAFT', 'ACTIVE', 'RETIRED']);
const EVIDENCE_VERIFICATION_STATUSES = Object.freeze([
  'VALID',
  'INVALID',
  'PARTIALLY_VERIFIABLE',
  'UNSUPPORTED_VERSION',
]);

const APPROVAL_REASON_CODES = Object.freeze({
  REQUIRED: 'APPROVAL_REQUIRED',
  PENDING: 'APPROVAL_PENDING',
  REJECTED: 'APPROVAL_REJECTED',
  EXPIRED: 'APPROVAL_EXPIRED',
  INVALIDATED: 'APPROVAL_INVALIDATED',
  NOT_FOUND: 'APPROVAL_REQUEST_NOT_FOUND',
  TENANT_MISMATCH: 'APPROVAL_TENANT_MISMATCH',
  APPROVER_NOT_ELIGIBLE: 'APPROVER_NOT_ELIGIBLE',
  APPROVER_DUPLICATE: 'APPROVER_DUPLICATE',
  SELF_APPROVAL: 'REQUESTER_SELF_APPROVAL_FORBIDDEN',
  STAGE_CONFLICT: 'APPROVAL_STAGE_CONFLICT',
  FINGERPRINT_MISMATCH: 'APPROVAL_FINGERPRINT_MISMATCH',
  GRANT_CONSUMED: 'APPROVAL_GRANT_ALREADY_CONSUMED',
  POLICY_REVOKED: 'APPROVAL_POLICY_REVOKED',
  RESOURCE_CHANGED: 'APPROVAL_RESOURCE_CHANGED',
});

const COMPLIANCE_SCHEMA_VERSION = 1;
const EVIDENCE_PACKAGE_VERSION = 1;
const EVIDENCE_HASH_ALGORITHM = 'sha256';
const DEFAULT_APPROVAL_EXPIRY_MS = 60 * 60 * 1000;
const MAX_APPROVAL_EXPIRY_MS = 7 * 24 * 60 * 60 * 1000;
const MAX_APPROVAL_STAGES = 10;
const MAX_APPROVERS_PER_STAGE = 20;
const MAX_LEGAL_HOLD_SELECTOR_VALUES = 100;
const MAX_EVIDENCE_EXPORT_EVENTS = 10_000;

module.exports = {
  APPROVAL_DECISIONS,
  APPROVAL_GRANT_STATUSES,
  APPROVAL_REASON_CODES,
  APPROVAL_REQUEST_STATUSES,
  APPROVAL_WORKFLOW_STATUSES,
  COMPLIANCE_SCHEMA_VERSION,
  DEFAULT_APPROVAL_EXPIRY_MS,
  EVIDENCE_EXPORT_STATUSES,
  EVIDENCE_HASH_ALGORITHM,
  EVIDENCE_PACKAGE_VERSION,
  EVIDENCE_RETENTION_CLASSES,
  EVIDENCE_VERIFICATION_STATUSES,
  HUMAN_ACTOR_TYPES,
  LEGAL_HOLD_STATUSES,
  MAX_APPROVAL_EXPIRY_MS,
  MAX_APPROVAL_STAGES,
  MAX_APPROVERS_PER_STAGE,
  MAX_EVIDENCE_EXPORT_EVENTS,
  MAX_LEGAL_HOLD_SELECTOR_VALUES,
  RETENTION_POLICY_STATUSES,
};
