const ENTERPRISE_OPERATIONS_SCHEMA_VERSION = 1;

const ORGANIZATION_LIFECYCLE_STATES = Object.freeze([
  'active',
  'suspending',
  'suspended',
  'reactivating',
  'archiving',
  'archived',
  'deletion_requested',
  'deletion_blocked',
  'deletion_in_progress',
  'deleted',
  'recovery_required',
]);

const WORKSPACE_LIFECYCLE_STATES = Object.freeze([
  'active',
  'read_only',
  'suspending',
  'suspended',
  'archived',
  'deletion_requested',
  'deletion_blocked',
  'deleted',
  'recovery_required',
]);

const MEMBERSHIP_LIFECYCLE_STATES = Object.freeze([
  'invited',
  'active',
  'suspended',
  'removal_pending',
  'removed',
  'deleted',
]);

const SERVICE_ACCOUNT_LIFECYCLE_STATES = Object.freeze([
  'active',
  'disabled',
  'rotation_required',
  'expired',
  'revoked',
  'deleted',
  'suspended',
]);

const MAINTENANCE_MODES = Object.freeze([
  'NONE',
  'READ_ONLY',
  'EXECUTION_BLOCKED',
  'DRAINING',
  'FULL_MAINTENANCE',
]);
const MAINTENANCE_STATUSES = Object.freeze([
  'DRAFT',
  'VALIDATED',
  'SCHEDULED',
  'ACTIVE',
  'RELEASED',
  'CANCELLED',
  'EXPIRED',
]);
const MAINTENANCE_SCOPES = Object.freeze([
  'PLATFORM',
  'ORGANIZATION',
  'WORKSPACE',
  'RUNTIME_ADAPTER',
  'CONNECTION',
]);

const ACCESS_REVIEW_STATUSES = Object.freeze([
  'DRAFT',
  'ACTIVE',
  'COMPLETED',
  'CANCELLED',
  'EXPIRED',
]);
const ACCESS_REVIEW_DECISIONS = Object.freeze(['KEEP', 'MODIFY', 'REVOKE', 'DEFER']);
const ACCESS_REMEDIATION_STATUSES = Object.freeze([
  'NOT_REQUIRED',
  'PENDING',
  'COMPLETED',
  'CONFLICT',
  'FAILED',
]);

const CONFIGURATION_STATUSES = Object.freeze([
  'DRAFT',
  'VALIDATED',
  'ACTIVE',
  'RETIRED',
  'ROLLED_BACK',
]);
const CONFIGURATION_CATEGORIES = Object.freeze([
  'INVOCATION_LIMITS',
  'WORKER_CAPACITY_LIMITS',
  'RETRY_DEFAULTS',
  'TIMEOUT_DEFAULTS',
  'MAINTENANCE_SETTINGS',
  'NOTIFICATION_PREFERENCES',
  'RETENTION_DEFAULTS',
  'APPROVAL_DEFAULTS',
  'CONNECTION_HEALTH_THRESHOLDS',
  'OPERATIONAL_ALERT_THRESHOLDS',
  'WORKSPACE_ENVIRONMENT',
  'FEATURE_AVAILABILITY',
]);

const INCIDENT_SEVERITIES = Object.freeze(['INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL']);
const INCIDENT_STATUSES = Object.freeze([
  'OPEN',
  'ACKNOWLEDGED',
  'INVESTIGATING',
  'MITIGATING',
  'MONITORING',
  'RESOLVED',
  'CLOSED',
]);
const SECURITY_EVENT_STATUSES = Object.freeze(['OPEN', 'ACKNOWLEDGED', 'RESOLVED']);

const TENANT_EXPORT_STATUSES = Object.freeze([
  'PENDING',
  'RUNNING',
  'FINALIZING',
  'COMPLETED',
  'CANCELLED',
  'FAILED',
  'RECOVERY_REQUIRED',
]);
const TENANT_DELETION_STATUSES = Object.freeze([
  'REQUESTED',
  'VALIDATING',
  'BLOCKED',
  'APPROVAL_PENDING',
  'SCHEDULED',
  'QUIESCING',
  'EXPORT_OPTIONAL',
  'DELETING',
  'VERIFYING',
  'COMPLETED',
  'FAILED',
  'RECOVERY_REQUIRED',
]);

const RECOVERY_STATUSES = Object.freeze(['OPEN', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED']);
const DR_PROVIDER_STATUSES = Object.freeze([
  'UNKNOWN',
  'HEALTHY',
  'DEGRADED',
  'FAILED',
  'NOT_CONFIGURED',
]);

const OPERATIONAL_ACCESS_TYPES = Object.freeze([
  'SAFE_READ',
  'MUTATION',
  'EXECUTION',
  'QUEUE_SUBMISSION',
  'WORKER_CLAIM',
  'CREDENTIAL_OPERATION',
  'PRIVILEGED_CONFIGURATION',
  'LIFECYCLE_CONTROL',
  'MAINTENANCE_CONTROL',
  'DELETION_CONTROL',
  'INCIDENT_RESPONSE',
  'HEALTH',
]);

const OPERATIONAL_REASON_CODES = Object.freeze({
  ORGANIZATION_NOT_ACTIVE: 'ORGANIZATION_NOT_ACTIVE',
  ORGANIZATION_SUSPENDED: 'ORGANIZATION_SUSPENDED',
  ORGANIZATION_ARCHIVED: 'ORGANIZATION_ARCHIVED',
  ORGANIZATION_DELETION_PENDING: 'ORGANIZATION_DELETION_PENDING',
  ORGANIZATION_DELETION_BLOCKED: 'ORGANIZATION_DELETION_BLOCKED',
  WORKSPACE_NOT_ACTIVE: 'WORKSPACE_NOT_ACTIVE',
  WORKSPACE_SUSPENDED: 'WORKSPACE_SUSPENDED',
  WORKSPACE_READ_ONLY: 'WORKSPACE_READ_ONLY',
  WORKSPACE_ARCHIVED: 'WORKSPACE_ARCHIVED',
  MAINTENANCE_MODE_ACTIVE: 'MAINTENANCE_MODE_ACTIVE',
  EXECUTION_DRAINING: 'EXECUTION_DRAINING',
  ADMINISTRATIVE_ACTION_BLOCKED: 'ADMINISTRATIVE_ACTION_BLOCKED',
  OPERATIONAL_STATE_INCONSISTENT: 'OPERATIONAL_STATE_INCONSISTENT',
});

module.exports = {
  ACCESS_REMEDIATION_STATUSES,
  ACCESS_REVIEW_DECISIONS,
  ACCESS_REVIEW_STATUSES,
  CONFIGURATION_CATEGORIES,
  CONFIGURATION_STATUSES,
  DR_PROVIDER_STATUSES,
  ENTERPRISE_OPERATIONS_SCHEMA_VERSION,
  INCIDENT_SEVERITIES,
  INCIDENT_STATUSES,
  MAINTENANCE_MODES,
  MAINTENANCE_SCOPES,
  MAINTENANCE_STATUSES,
  MEMBERSHIP_LIFECYCLE_STATES,
  OPERATIONAL_ACCESS_TYPES,
  OPERATIONAL_REASON_CODES,
  ORGANIZATION_LIFECYCLE_STATES,
  RECOVERY_STATUSES,
  SECURITY_EVENT_STATUSES,
  SERVICE_ACCOUNT_LIFECYCLE_STATES,
  TENANT_DELETION_STATUSES,
  TENANT_EXPORT_STATUSES,
  WORKSPACE_LIFECYCLE_STATES,
};
