const PERMISSION_REGISTRY_VERSION = 6;
const PERMISSION_REGISTRY_ID = `permission-registry.v${PERMISSION_REGISTRY_VERSION}`;

const RiskLevels = Object.freeze({
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
});

const permissionDefinitions = [
  {
    id: 'organization.read',
    description: 'Read organization metadata and hierarchy.',
    category: 'Organization',
    riskLevel: RiskLevels.LOW,
    defaultRoles: ['organization_owner', 'organization_admin', 'security_admin', 'auditor'],
    auditRequired: true,
  },
  {
    id: 'organization.manage',
    description: 'Manage organization settings and enterprise configuration.',
    category: 'Organization',
    riskLevel: RiskLevels.CRITICAL,
    defaultRoles: ['organization_owner', 'organization_admin'],
    auditRequired: true,
  },
  {
    id: 'workspace.read',
    description: 'Read workspace metadata and membership.',
    category: 'Workspace',
    riskLevel: RiskLevels.LOW,
    defaultRoles: [
      'organization_owner',
      'organization_admin',
      'security_admin',
      'workspace_admin',
      'operator',
      'developer',
      'auditor',
      'viewer',
    ],
    auditRequired: true,
  },
  {
    id: 'workspace.manage',
    description: 'Create, update, and administer workspaces.',
    category: 'Workspace',
    riskLevel: RiskLevels.HIGH,
    defaultRoles: ['organization_owner', 'organization_admin', 'security_admin', 'workspace_admin'],
    auditRequired: true,
  },
  {
    id: 'team.read',
    description: 'Read teams and team membership.',
    category: 'Identity',
    riskLevel: RiskLevels.LOW,
    defaultRoles: [
      'organization_owner',
      'organization_admin',
      'security_admin',
      'workspace_admin',
      'auditor',
      'viewer',
    ],
    auditRequired: true,
  },
  {
    id: 'team.manage',
    description: 'Create, update, and manage teams.',
    category: 'Identity',
    riskLevel: RiskLevels.HIGH,
    defaultRoles: ['organization_owner', 'organization_admin', 'security_admin', 'workspace_admin'],
    auditRequired: true,
  },
  {
    id: 'user.read',
    description: 'Read enterprise users and memberships.',
    category: 'Identity',
    riskLevel: RiskLevels.LOW,
    defaultRoles: [
      'organization_owner',
      'organization_admin',
      'security_admin',
      'workspace_admin',
      'auditor',
      'viewer',
    ],
    auditRequired: true,
  },
  {
    id: 'user.manage',
    description: 'Create, update, suspend, and assign enterprise users.',
    category: 'Identity',
    riskLevel: RiskLevels.HIGH,
    defaultRoles: ['organization_owner', 'organization_admin', 'security_admin', 'workspace_admin'],
    auditRequired: true,
  },
  {
    id: 'service_account.read',
    description: 'Read service accounts and their scopes.',
    category: 'Identity',
    riskLevel: RiskLevels.MEDIUM,
    defaultRoles: ['organization_owner', 'organization_admin', 'security_admin', 'auditor'],
    auditRequired: true,
  },
  {
    id: 'service_account.manage',
    description: 'Create, rotate, suspend, and scope service accounts.',
    category: 'Identity',
    riskLevel: RiskLevels.CRITICAL,
    defaultRoles: ['organization_owner', 'organization_admin', 'security_admin'],
    auditRequired: true,
  },
  {
    id: 'role.read',
    description: 'Read built-in and custom roles.',
    category: 'Authorization',
    riskLevel: RiskLevels.LOW,
    defaultRoles: [
      'organization_owner',
      'organization_admin',
      'security_admin',
      'workspace_admin',
      'auditor',
      'viewer',
    ],
    auditRequired: true,
  },
  {
    id: 'role.manage',
    description: 'Create and update custom role definitions.',
    category: 'Authorization',
    riskLevel: RiskLevels.CRITICAL,
    defaultRoles: ['organization_owner', 'organization_admin', 'security_admin'],
    auditRequired: true,
  },
  {
    id: 'permission.read',
    description: 'Inspect the permission registry and metadata.',
    category: 'Authorization',
    riskLevel: RiskLevels.LOW,
    defaultRoles: [
      'organization_owner',
      'organization_admin',
      'security_admin',
      'workspace_admin',
      'auditor',
      'viewer',
    ],
    auditRequired: true,
  },
  {
    id: 'passport.read',
    description: 'Read Agent Passport metadata.',
    category: 'Passport',
    riskLevel: RiskLevels.LOW,
    defaultRoles: [
      'organization_owner',
      'organization_admin',
      'workspace_admin',
      'operator',
      'developer',
      'auditor',
      'viewer',
    ],
    auditRequired: true,
  },
  {
    id: 'passport.create',
    description: 'Create and update Agent Passports and install keys.',
    category: 'Passport',
    riskLevel: RiskLevels.HIGH,
    defaultRoles: ['organization_owner', 'organization_admin', 'workspace_admin', 'developer'],
    auditRequired: true,
  },
  {
    id: 'passport.delete',
    description: 'Suspend, revoke, or delete Agent Passport access.',
    category: 'Passport',
    riskLevel: RiskLevels.CRITICAL,
    defaultRoles: ['organization_owner', 'organization_admin', 'workspace_admin'],
    auditRequired: true,
  },
  {
    id: 'connection.read',
    description: 'Read workspace connection metadata.',
    category: 'Connection',
    riskLevel: RiskLevels.LOW,
    defaultRoles: [
      'organization_owner',
      'organization_admin',
      'workspace_admin',
      'operator',
      'developer',
      'auditor',
      'viewer',
    ],
    auditRequired: true,
  },
  {
    id: 'connection.create',
    description: 'Resolve install keys and create workspace connections.',
    category: 'Connection',
    riskLevel: RiskLevels.HIGH,
    defaultRoles: ['organization_owner', 'organization_admin', 'workspace_admin', 'developer'],
    auditRequired: true,
  },
  {
    id: 'connection.invoke',
    description: 'Invoke a connected Agent Passport capability.',
    category: 'Connection',
    riskLevel: RiskLevels.HIGH,
    defaultRoles: [
      'organization_owner',
      'organization_admin',
      'workspace_admin',
      'operator',
      'developer',
    ],
    auditRequired: true,
  },
  {
    id: 'connection.delete',
    description: 'Disconnect or remove workspace connections.',
    category: 'Connection',
    riskLevel: RiskLevels.CRITICAL,
    defaultRoles: ['organization_owner', 'organization_admin', 'workspace_admin'],
    auditRequired: true,
  },
  ...[
    [
      'orchestration.definition.read',
      'Read tenant-scoped orchestration definitions and safe graph metadata.',
      'LOW',
      [
        'organization_owner',
        'organization_admin',
        'security_admin',
        'workspace_admin',
        'operator',
        'developer',
        'auditor',
        'viewer',
      ],
    ],
    [
      'orchestration.definition.create',
      'Create a tenant-scoped orchestration definition draft.',
      'HIGH',
      ['organization_owner', 'organization_admin', 'workspace_admin', 'developer'],
    ],
    [
      'orchestration.definition.update',
      'Update an orchestration draft or create a successor version.',
      'HIGH',
      ['organization_owner', 'organization_admin', 'workspace_admin', 'developer'],
    ],
    [
      'orchestration.definition.validate',
      'Validate orchestration graph, schema, connection, and capability references.',
      'HIGH',
      ['organization_owner', 'organization_admin', 'security_admin', 'workspace_admin', 'developer'],
    ],
    [
      'orchestration.definition.activate',
      'Activate an immutable validated orchestration version.',
      'CRITICAL',
      ['organization_owner', 'organization_admin', 'security_admin', 'workspace_admin'],
    ],
    [
      'orchestration.definition.archive',
      'Archive an orchestration version without changing existing runs.',
      'HIGH',
      ['organization_owner', 'organization_admin', 'workspace_admin'],
    ],
    [
      'orchestration.run.create',
      'Start a durable orchestration run.',
      'HIGH',
      ['organization_owner', 'organization_admin', 'workspace_admin', 'operator', 'developer'],
    ],
    [
      'orchestration.run.read',
      'Read orchestration run state and safe node metadata.',
      'LOW',
      [
        'organization_owner',
        'organization_admin',
        'security_admin',
        'workspace_admin',
        'operator',
        'developer',
        'auditor',
        'viewer',
      ],
    ],
    [
      'orchestration.run.cancel',
      'Request durable cancellation of an orchestration run.',
      'HIGH',
      ['organization_owner', 'organization_admin', 'workspace_admin', 'operator', 'developer'],
    ],
    [
      'orchestration.node.execute',
      'Execute a claimed orchestration node through the Runtime Gateway.',
      'HIGH',
      ['organization_owner', 'organization_admin', 'workspace_admin', 'operator'],
    ],
    [
      'orchestration.node.retry',
      'Retry a platform-classified retryable orchestration node failure.',
      'HIGH',
      ['organization_owner', 'organization_admin', 'workspace_admin', 'operator'],
    ],
  ].map(([id, description, riskLevel, defaultRoles]) => ({
    id,
    description,
    category: 'Orchestration',
    riskLevel: RiskLevels[riskLevel],
    defaultRoles,
    auditRequired: true,
  })),
  {
    id: 'credential.read',
    description: 'Read credential metadata without exposing secrets.',
    category: 'Credential',
    riskLevel: RiskLevels.HIGH,
    defaultRoles: ['organization_owner', 'organization_admin', 'security_admin', 'auditor'],
    auditRequired: true,
  },
  {
    id: 'credential.rotate',
    description: 'Create, replace, revoke, or rotate runtime credentials.',
    category: 'Credential',
    riskLevel: RiskLevels.CRITICAL,
    defaultRoles: [
      'organization_owner',
      'organization_admin',
      'security_admin',
      'workspace_admin',
      'developer',
    ],
    auditRequired: true,
  },
  {
    id: 'secret.metadata.read',
    description: 'Read governed secret metadata and version history without plaintext access.',
    category: 'Secret Governance',
    riskLevel: RiskLevels.MEDIUM,
    defaultRoles: [
      'organization_owner',
      'organization_admin',
      'security_admin',
      'workspace_admin',
      'operator',
      'auditor',
      'viewer',
    ],
    auditRequired: true,
  },
  {
    id: 'secret.create',
    description: 'Create a governed logical secret and encrypted initial version.',
    category: 'Secret Governance',
    riskLevel: RiskLevels.CRITICAL,
    defaultRoles: ['organization_owner', 'organization_admin', 'security_admin'],
    auditRequired: true,
  },
  {
    id: 'secret.update',
    description: 'Update safe secret metadata and add pending encrypted versions.',
    category: 'Secret Governance',
    riskLevel: RiskLevels.HIGH,
    defaultRoles: ['organization_owner', 'organization_admin', 'security_admin'],
    auditRequired: true,
  },
  {
    id: 'secret.rotate',
    description: 'Validate and atomically rotate governed credential versions.',
    category: 'Secret Governance',
    riskLevel: RiskLevels.CRITICAL,
    defaultRoles: ['organization_owner', 'organization_admin', 'security_admin'],
    auditRequired: true,
  },
  {
    id: 'secret.revoke',
    description: 'Disable or revoke logical secrets, versions, and bindings.',
    category: 'Secret Governance',
    riskLevel: RiskLevels.CRITICAL,
    defaultRoles: ['organization_owner', 'organization_admin', 'security_admin'],
    auditRequired: true,
  },
  {
    id: 'secret.destroy',
    description: 'Cryptographically destroy retained secret-version ciphertext.',
    category: 'Secret Governance',
    riskLevel: RiskLevels.CRITICAL,
    defaultRoles: ['organization_owner', 'security_admin'],
    auditRequired: true,
  },
  {
    id: 'secret.binding.read',
    description: 'Read credential binding metadata without resolving credentials.',
    category: 'Secret Governance',
    riskLevel: RiskLevels.MEDIUM,
    defaultRoles: [
      'organization_owner',
      'organization_admin',
      'security_admin',
      'workspace_admin',
      'operator',
      'auditor',
    ],
    auditRequired: true,
  },
  {
    id: 'secret.binding.manage',
    description: 'Create, update, disable, or revoke tenant-safe credential bindings.',
    category: 'Secret Governance',
    riskLevel: RiskLevels.CRITICAL,
    defaultRoles: ['organization_owner', 'organization_admin', 'security_admin'],
    auditRequired: true,
  },
  {
    id: 'secret.health.read',
    description: 'Read safe provider credential-health metadata.',
    category: 'Secret Governance',
    riskLevel: RiskLevels.MEDIUM,
    defaultRoles: [
      'organization_owner',
      'organization_admin',
      'security_admin',
      'operator',
      'auditor',
    ],
    auditRequired: true,
  },
  {
    id: 'secret.health.check',
    description: 'Trigger a supported, non-destructive provider credential validation.',
    category: 'Secret Governance',
    riskLevel: RiskLevels.HIGH,
    defaultRoles: ['organization_owner', 'organization_admin', 'security_admin', 'operator'],
    auditRequired: true,
  },
  {
    id: 'secret.audit.read',
    description: 'Read redacted secret lifecycle and runtime-use audit evidence.',
    category: 'Secret Governance',
    riskLevel: RiskLevels.HIGH,
    defaultRoles: ['organization_owner', 'organization_admin', 'security_admin', 'auditor'],
    auditRequired: true,
  },
  {
    id: 'encryption-key.metadata.read',
    description: 'Read encryption-provider health and aggregate key-version usage counts.',
    category: 'Secret Governance',
    riskLevel: RiskLevels.HIGH,
    defaultRoles: ['organization_owner', 'organization_admin', 'security_admin', 'auditor'],
    auditRequired: true,
  },
  {
    id: 'encryption-key.rotate',
    description: 'Start or resume tenant-safe secret ciphertext re-encryption.',
    category: 'Secret Governance',
    riskLevel: RiskLevels.CRITICAL,
    defaultRoles: ['organization_owner', 'security_admin'],
    auditRequired: true,
  },
  {
    id: 'audit.read',
    description: 'Read redacted audit events.',
    category: 'Audit',
    riskLevel: RiskLevels.HIGH,
    defaultRoles: ['organization_owner', 'organization_admin', 'security_admin', 'auditor'],
    auditRequired: true,
  },
  {
    id: 'invocation.read',
    description: 'Read invocation state, attempts, and safe metadata.',
    category: 'Invocation',
    riskLevel: RiskLevels.LOW,
    defaultRoles: [
      'organization_owner',
      'organization_admin',
      'workspace_admin',
      'operator',
      'developer',
      'auditor',
      'viewer',
    ],
    auditRequired: true,
  },
  {
    id: 'invocation.retry',
    description: 'Request safe manual invocation retry.',
    category: 'Invocation',
    riskLevel: RiskLevels.HIGH,
    defaultRoles: ['organization_owner', 'organization_admin', 'workspace_admin', 'operator'],
    auditRequired: true,
  },
  {
    id: 'invocation.cancel',
    description: 'Cancel or resolve invocation control state.',
    category: 'Invocation',
    riskLevel: RiskLevels.HIGH,
    defaultRoles: ['organization_owner', 'organization_admin', 'workspace_admin', 'operator'],
    auditRequired: true,
  },
  {
    id: 'worker.read',
    description: 'Read aggregate runtime worker and durable queue health.',
    category: 'Operations',
    riskLevel: RiskLevels.MEDIUM,
    defaultRoles: [
      'organization_owner',
      'organization_admin',
      'workspace_admin',
      'operator',
      'auditor',
    ],
    auditRequired: true,
  },
  {
    id: 'worker.manage',
    description: 'Run bounded durable worker recovery and reconciliation controls.',
    category: 'Operations',
    riskLevel: RiskLevels.CRITICAL,
    defaultRoles: ['organization_owner', 'organization_admin', 'workspace_admin', 'operator'],
    auditRequired: true,
  },
  {
    id: 'operations.read',
    description: 'Read operational summaries, alerts, and safety metrics.',
    category: 'Operations',
    riskLevel: RiskLevels.MEDIUM,
    defaultRoles: [
      'organization_owner',
      'organization_admin',
      'workspace_admin',
      'operator',
      'auditor',
      'viewer',
    ],
    auditRequired: true,
  },
  {
    id: 'operations.manage',
    description: 'Acknowledge alerts and run bounded operational controls.',
    category: 'Operations',
    riskLevel: RiskLevels.HIGH,
    defaultRoles: ['organization_owner', 'organization_admin', 'workspace_admin', 'operator'],
    auditRequired: true,
  },
  {
    id: 'policy.read',
    description: 'Read policy definitions, versions, and the trusted attribute catalog.',
    category: 'Authorization',
    riskLevel: RiskLevels.LOW,
    defaultRoles: ['organization_owner', 'organization_admin', 'security_admin', 'auditor'],
    auditRequired: true,
  },
  {
    id: 'policy.manage',
    description: 'Legacy aggregate permission for policy administration.',
    category: 'Authorization',
    riskLevel: RiskLevels.CRITICAL,
    defaultRoles: ['organization_owner', 'organization_admin', 'security_admin'],
    auditRequired: true,
  },
  {
    id: 'policy.create',
    description: 'Create a tenant-scoped draft policy.',
    category: 'Authorization',
    riskLevel: RiskLevels.HIGH,
    defaultRoles: ['organization_owner', 'organization_admin', 'security_admin'],
    auditRequired: true,
  },
  {
    id: 'policy.update',
    description: 'Update a draft policy or create a new version.',
    category: 'Authorization',
    riskLevel: RiskLevels.HIGH,
    defaultRoles: ['organization_owner', 'organization_admin', 'security_admin'],
    auditRequired: true,
  },
  {
    id: 'policy.validate',
    description: 'Validate policy syntax, targets, and tenant references.',
    category: 'Authorization',
    riskLevel: RiskLevels.MEDIUM,
    defaultRoles: ['organization_owner', 'organization_admin', 'security_admin'],
    auditRequired: true,
  },
  {
    id: 'policy.simulate',
    description: 'Run a non-mutating tenant-scoped policy simulation.',
    category: 'Authorization',
    riskLevel: RiskLevels.HIGH,
    defaultRoles: ['organization_owner', 'organization_admin', 'security_admin', 'auditor'],
    auditRequired: true,
  },
  {
    id: 'policy.activate',
    description: 'Atomically activate a validated draft policy version.',
    category: 'Authorization',
    riskLevel: RiskLevels.CRITICAL,
    defaultRoles: ['organization_owner', 'organization_admin', 'security_admin'],
    auditRequired: true,
  },
  {
    id: 'policy.retire',
    description: 'Retire an active policy version while retaining history.',
    category: 'Authorization',
    riskLevel: RiskLevels.CRITICAL,
    defaultRoles: ['organization_owner', 'organization_admin', 'security_admin'],
    auditRequired: true,
  },
  {
    id: 'policy.audit.read',
    description: 'Read policy decision and lifecycle audit evidence.',
    category: 'Authorization',
    riskLevel: RiskLevels.MEDIUM,
    defaultRoles: ['organization_owner', 'organization_admin', 'security_admin', 'auditor'],
    auditRequired: true,
  },
  ...[
    [
      'approval.workflow.read',
      'Read approval workflow definitions and version history.',
      'MEDIUM',
      ['organization_owner', 'organization_admin', 'security_admin', 'auditor'],
    ],
    [
      'approval.workflow.create',
      'Create tenant-scoped approval workflow drafts.',
      'HIGH',
      ['organization_owner', 'organization_admin', 'security_admin'],
    ],
    [
      'approval.workflow.update',
      'Update draft approval workflows and create new versions.',
      'HIGH',
      ['organization_owner', 'organization_admin', 'security_admin'],
    ],
    [
      'approval.workflow.activate',
      'Activate an immutable approval workflow version.',
      'CRITICAL',
      ['organization_owner', 'security_admin'],
    ],
    [
      'approval.workflow.retire',
      'Retire an active approval workflow version.',
      'CRITICAL',
      ['organization_owner', 'security_admin'],
    ],
    [
      'approval.request.read',
      'Read tenant-scoped approval requests and safe decision history.',
      'MEDIUM',
      ['organization_owner', 'organization_admin', 'security_admin', 'workspace_admin', 'auditor'],
    ],
    [
      'approval.request.create',
      'Create an approval request bound to one exact action.',
      'HIGH',
      [
        'organization_owner',
        'organization_admin',
        'security_admin',
        'workspace_admin',
        'operator',
        'developer',
      ],
    ],
    [
      'approval.request.cancel',
      'Cancel an unconsumed approval request.',
      'HIGH',
      ['organization_owner', 'organization_admin', 'security_admin', 'workspace_admin'],
    ],
    [
      'approval.request.approve',
      'Approve an eligible stage of a governed request.',
      'CRITICAL',
      ['organization_owner', 'organization_admin', 'security_admin', 'workspace_admin'],
    ],
    [
      'approval.request.reject',
      'Reject an eligible stage of a governed request.',
      'HIGH',
      ['organization_owner', 'organization_admin', 'security_admin', 'workspace_admin'],
    ],
    [
      'approval.audit.read',
      'Read redacted approval lifecycle evidence.',
      'HIGH',
      ['organization_owner', 'organization_admin', 'security_admin', 'auditor'],
    ],
    [
      'evidence.read',
      'Query normalized, redacted evidence event metadata.',
      'HIGH',
      ['organization_owner', 'organization_admin', 'security_admin', 'auditor'],
    ],
    [
      'evidence.export',
      'Create bounded tenant-scoped evidence packages.',
      'CRITICAL',
      ['organization_owner', 'organization_admin', 'security_admin', 'auditor'],
    ],
    [
      'evidence.download',
      'Download a completed evidence package through authorized access.',
      'CRITICAL',
      ['organization_owner', 'organization_admin', 'security_admin', 'auditor'],
    ],
    [
      'evidence.verify',
      'Verify evidence package and audit-chain integrity.',
      'HIGH',
      ['organization_owner', 'organization_admin', 'security_admin', 'auditor'],
    ],
    [
      'audit.integrity.read',
      'Read audit-chain and checkpoint status.',
      'HIGH',
      ['organization_owner', 'organization_admin', 'security_admin', 'auditor'],
    ],
    [
      'audit.integrity.verify',
      'Run tenant-scoped audit-chain verification.',
      'CRITICAL',
      ['organization_owner', 'security_admin', 'auditor'],
    ],
    [
      'audit.retention.read',
      'Read retention policies and safe deletion previews.',
      'HIGH',
      ['organization_owner', 'organization_admin', 'security_admin', 'auditor'],
    ],
    [
      'audit.retention.manage',
      'Activate retention policies and run explicit deletion jobs.',
      'CRITICAL',
      ['organization_owner', 'security_admin'],
    ],
    [
      'legal-hold.read',
      'Read tenant-scoped legal-hold metadata.',
      'HIGH',
      ['organization_owner', 'organization_admin', 'security_admin', 'auditor'],
    ],
    [
      'legal-hold.create',
      'Create and activate a bounded legal hold.',
      'CRITICAL',
      ['organization_owner', 'security_admin'],
    ],
    [
      'legal-hold.release',
      'Release a legal hold without immediately deleting evidence.',
      'CRITICAL',
      ['organization_owner', 'security_admin'],
    ],
    [
      'control.read',
      'Read the internal control catalog and informational mappings.',
      'MEDIUM',
      ['organization_owner', 'organization_admin', 'security_admin', 'auditor'],
    ],
    [
      'control.manage',
      'Manage internal control mappings and implementation metadata.',
      'CRITICAL',
      ['organization_owner', 'security_admin'],
    ],
    [
      'compliance.report.read',
      'Generate tenant-scoped compliance activity reports.',
      'HIGH',
      ['organization_owner', 'organization_admin', 'security_admin', 'auditor'],
    ],
  ].map(([id, description, riskLevel, defaultRoles]) => ({
    id,
    description,
    category: id.startsWith('approval.')
      ? 'Approval Governance'
      : id.startsWith('legal-hold.')
        ? 'Legal Hold'
        : id.startsWith('control.') || id.startsWith('compliance.')
          ? 'Compliance'
          : 'Audit Evidence',
    riskLevel: RiskLevels[riskLevel],
    defaultRoles,
    auditRequired: true,
  })),
  ...[
    [
      'organization.lifecycle.read',
      'Read organization lifecycle state and transition history.',
      'HIGH',
      ['organization_owner', 'organization_admin', 'security_admin', 'auditor'],
      'Enterprise Operations',
    ],
    [
      'organization.suspend',
      'Suspend organization execution through governed lifecycle transitions.',
      'CRITICAL',
      ['organization_owner', 'security_admin'],
      'Enterprise Operations',
    ],
    [
      'organization.reactivate',
      'Reactivate a suspended organization after readiness validation.',
      'CRITICAL',
      ['organization_owner', 'security_admin'],
      'Enterprise Operations',
    ],
    [
      'organization.archive',
      'Archive an organization while preserving governed history.',
      'CRITICAL',
      ['organization_owner'],
      'Enterprise Operations',
    ],
    [
      'organization.delete.request',
      'Request a governed durable organization deletion workflow.',
      'CRITICAL',
      ['organization_owner'],
      'Tenant Data Management',
    ],
    [
      'organization.delete.execute',
      'Execute an approved organization deletion workflow.',
      'CRITICAL',
      ['organization_owner'],
      'Tenant Data Management',
    ],
    [
      'workspace.lifecycle.read',
      'Read workspace lifecycle state and transition history.',
      'HIGH',
      ['organization_owner', 'organization_admin', 'security_admin', 'workspace_admin', 'auditor'],
      'Enterprise Operations',
    ],
    [
      'workspace.suspend',
      'Suspend one workspace without affecting unrelated workspaces.',
      'CRITICAL',
      ['organization_owner', 'organization_admin', 'security_admin', 'workspace_admin'],
      'Enterprise Operations',
    ],
    [
      'workspace.reactivate',
      'Reactivate one workspace after readiness validation.',
      'CRITICAL',
      ['organization_owner', 'organization_admin', 'security_admin', 'workspace_admin'],
      'Enterprise Operations',
    ],
    [
      'workspace.archive',
      'Archive a workspace while preserving governed history.',
      'CRITICAL',
      ['organization_owner', 'organization_admin', 'security_admin'],
      'Enterprise Operations',
    ],
    [
      'workspace.delete.request',
      'Request governed deletion of one workspace.',
      'CRITICAL',
      ['organization_owner', 'organization_admin', 'security_admin'],
      'Tenant Data Management',
    ],
    [
      'maintenance.read',
      'Read scoped maintenance windows and drain status.',
      'MEDIUM',
      [
        'organization_owner',
        'organization_admin',
        'security_admin',
        'workspace_admin',
        'operator',
        'auditor',
      ],
      'Maintenance',
    ],
    [
      'maintenance.manage',
      'Create and validate scoped maintenance windows.',
      'HIGH',
      ['organization_owner', 'organization_admin', 'security_admin', 'workspace_admin', 'operator'],
      'Maintenance',
    ],
    [
      'maintenance.activate',
      'Activate scoped maintenance or draining behavior.',
      'CRITICAL',
      ['organization_owner', 'organization_admin', 'security_admin', 'operator'],
      'Maintenance',
    ],
    [
      'maintenance.release',
      'Release active scoped maintenance after validation.',
      'CRITICAL',
      ['organization_owner', 'organization_admin', 'security_admin', 'operator'],
      'Maintenance',
    ],
    [
      'membership.lifecycle.read',
      'Read enterprise membership lifecycle and history.',
      'HIGH',
      ['organization_owner', 'organization_admin', 'security_admin', 'workspace_admin', 'auditor'],
      'Identity Operations',
    ],
    [
      'membership.suspend',
      'Suspend a membership and immediately remove new authorization.',
      'CRITICAL',
      ['organization_owner', 'organization_admin', 'security_admin', 'workspace_admin'],
      'Identity Operations',
    ],
    [
      'membership.restore',
      'Restore an eligible suspended membership.',
      'HIGH',
      ['organization_owner', 'organization_admin', 'security_admin', 'workspace_admin'],
      'Identity Operations',
    ],
    [
      'membership.remove',
      'Govern removal of membership and scoped access assignments.',
      'CRITICAL',
      ['organization_owner', 'organization_admin', 'security_admin'],
      'Identity Operations',
    ],
    [
      'service-account.lifecycle.read',
      'Read service-account lifecycle and recent governed use.',
      'HIGH',
      ['organization_owner', 'organization_admin', 'security_admin', 'workspace_admin', 'auditor'],
      'Identity Operations',
    ],
    [
      'service-account.disable',
      'Disable service-account governed use.',
      'CRITICAL',
      ['organization_owner', 'organization_admin', 'security_admin', 'workspace_admin'],
      'Identity Operations',
    ],
    [
      'service-account.rotate',
      'Require or record governed service-account authentication rotation.',
      'CRITICAL',
      ['organization_owner', 'organization_admin', 'security_admin'],
      'Identity Operations',
    ],
    [
      'service-account.revoke',
      'Permanently revoke a service account.',
      'CRITICAL',
      ['organization_owner', 'security_admin'],
      'Identity Operations',
    ],
    [
      'access-review.read',
      'Read tenant-scoped access review campaigns and items.',
      'HIGH',
      ['organization_owner', 'organization_admin', 'security_admin', 'workspace_admin', 'auditor'],
      'Access Review',
    ],
    [
      'access-review.create',
      'Create tenant-scoped access review campaign drafts.',
      'HIGH',
      ['organization_owner', 'organization_admin', 'security_admin'],
      'Access Review',
    ],
    [
      'access-review.manage',
      'Activate, close, or cancel access review campaigns.',
      'CRITICAL',
      ['organization_owner', 'organization_admin', 'security_admin'],
      'Access Review',
    ],
    [
      'access-review.decide',
      'Record a review decision without silently changing access.',
      'HIGH',
      ['organization_owner', 'organization_admin', 'security_admin', 'workspace_admin'],
      'Access Review',
    ],
    [
      'access-review.remediate',
      'Execute governed and reauthorized access remediation.',
      'CRITICAL',
      ['organization_owner', 'organization_admin', 'security_admin'],
      'Access Review',
    ],
    [
      'configuration.read',
      'Read versioned operational configuration metadata.',
      'MEDIUM',
      [
        'organization_owner',
        'organization_admin',
        'security_admin',
        'workspace_admin',
        'operator',
        'auditor',
      ],
      'Configuration Governance',
    ],
    [
      'configuration.create',
      'Create operational configuration drafts.',
      'HIGH',
      ['organization_owner', 'organization_admin', 'security_admin', 'workspace_admin', 'operator'],
      'Configuration Governance',
    ],
    [
      'configuration.validate',
      'Validate operational configuration without activation.',
      'HIGH',
      ['organization_owner', 'organization_admin', 'security_admin', 'operator'],
      'Configuration Governance',
    ],
    [
      'configuration.activate',
      'Atomically activate an immutable configuration version.',
      'CRITICAL',
      ['organization_owner', 'organization_admin', 'security_admin'],
      'Configuration Governance',
    ],
    [
      'configuration.rollback',
      'Safely activate a prior configuration as a new version.',
      'CRITICAL',
      ['organization_owner', 'organization_admin', 'security_admin'],
      'Configuration Governance',
    ],
    [
      'incident.read',
      'Read tenant-scoped incidents and safe timelines.',
      'HIGH',
      [
        'organization_owner',
        'organization_admin',
        'security_admin',
        'workspace_admin',
        'operator',
        'auditor',
      ],
      'Incident Management',
    ],
    [
      'incident.create',
      'Create a tenant-scoped operational incident.',
      'HIGH',
      ['organization_owner', 'organization_admin', 'security_admin', 'workspace_admin', 'operator'],
      'Incident Management',
    ],
    [
      'incident.manage',
      'Acknowledge, assign, resolve, and close incidents.',
      'HIGH',
      ['organization_owner', 'organization_admin', 'security_admin', 'operator'],
      'Incident Management',
    ],
    [
      'incident.respond',
      'Execute a governed incident response action.',
      'CRITICAL',
      ['organization_owner', 'security_admin', 'operator'],
      'Incident Management',
    ],
    [
      'security-event.read',
      'Read normalized tenant-scoped security events.',
      'HIGH',
      ['organization_owner', 'organization_admin', 'security_admin', 'auditor'],
      'Security Operations',
    ],
    [
      'security-event.manage',
      'Acknowledge and resolve normalized security events.',
      'CRITICAL',
      ['organization_owner', 'security_admin'],
      'Security Operations',
    ],
    [
      'tenant-export.create',
      'Create a redacted asynchronous tenant data export.',
      'CRITICAL',
      ['organization_owner', 'organization_admin', 'security_admin'],
      'Tenant Data Management',
    ],
    [
      'tenant-export.read',
      'Read tenant data export status and safe manifests.',
      'HIGH',
      ['organization_owner', 'organization_admin', 'security_admin', 'auditor'],
      'Tenant Data Management',
    ],
    [
      'tenant-export.download',
      'Download a tenant export using short-lived authorized access.',
      'CRITICAL',
      ['organization_owner', 'security_admin'],
      'Tenant Data Management',
    ],
    [
      'tenant-deletion.read',
      'Read deletion previews, blockers, progress, and evidence.',
      'CRITICAL',
      ['organization_owner', 'security_admin', 'auditor'],
      'Tenant Data Management',
    ],
    [
      'tenant-deletion.request',
      'Request a governed durable tenant deletion.',
      'CRITICAL',
      ['organization_owner'],
      'Tenant Data Management',
    ],
    [
      'tenant-deletion.approve',
      'Approve a tenant deletion after blocker review.',
      'CRITICAL',
      ['organization_owner', 'security_admin'],
      'Tenant Data Management',
    ],
    [
      'tenant-deletion.execute',
      'Execute an approved, scoped, resumable tenant deletion.',
      'CRITICAL',
      ['organization_owner'],
      'Tenant Data Management',
    ],
    [
      'recovery.read',
      'Read operational recovery records and safe next steps.',
      'HIGH',
      ['organization_owner', 'organization_admin', 'security_admin', 'operator', 'auditor'],
      'Recovery',
    ],
    [
      'recovery.manage',
      'Assign or execute idempotent operational recovery actions.',
      'CRITICAL',
      ['organization_owner', 'security_admin', 'operator'],
      'Recovery',
    ],
    [
      'dr-status.read',
      'Read worker and administrative drain status.',
      'MEDIUM',
      [
        'organization_owner',
        'organization_admin',
        'security_admin',
        'workspace_admin',
        'operator',
        'auditor',
      ],
      'Recovery',
    ],
    [
      'operations.admin.read',
      'Read the enterprise administrative operations dashboard.',
      'HIGH',
      [
        'organization_owner',
        'organization_admin',
        'security_admin',
        'workspace_admin',
        'operator',
        'auditor',
      ],
      'Enterprise Operations',
    ],
  ].map(([id, description, riskLevel, defaultRoles, category]) => ({
    id,
    description,
    category,
    riskLevel: RiskLevels[riskLevel],
    defaultRoles,
    auditRequired: true,
  })),
].map((permission) =>
  Object.freeze({
    registryId: PERMISSION_REGISTRY_ID,
    registryVersion: PERMISSION_REGISTRY_VERSION,
    ...permission,
  }),
);

const permissionsById = new Map(
  permissionDefinitions.map((permission) => [permission.id, permission]),
);

function getPermission(permissionId) {
  return permissionsById.get(permissionId);
}

function hasPermission(permissionId) {
  return permissionsById.has(permissionId);
}

function listPermissions() {
  return permissionDefinitions.map((permission) => ({ ...permission }));
}

function getPermissionRegistry() {
  return {
    id: PERMISSION_REGISTRY_ID,
    name: `Permission Registry v${PERMISSION_REGISTRY_VERSION}`,
    version: PERMISSION_REGISTRY_VERSION,
    permissions: listPermissions(),
  };
}

module.exports = {
  PERMISSION_REGISTRY_ID,
  PERMISSION_REGISTRY_VERSION,
  RiskLevels,
  getPermission,
  getPermissionRegistry,
  hasPermission,
  listPermissions,
};
