const PERMISSION_REGISTRY_VERSION = 1;
const PERMISSION_REGISTRY_ID = `permission-registry.v${PERMISSION_REGISTRY_VERSION}`;

const RiskLevels = Object.freeze({
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
});

const permissionDefinitions = [
  {
    id: 'organization.read',
    description: 'Read organization metadata and hierarchy.',
    category: 'Organization',
    riskLevel: RiskLevels.LOW,
    defaultRoles: ['organization_owner', 'organization_admin', 'security_admin', 'auditor'],
    auditRequired: true,
  },
  {
    id: 'organization.manage',
    description: 'Manage organization settings and enterprise configuration.',
    category: 'Organization',
    riskLevel: RiskLevels.CRITICAL,
    defaultRoles: ['organization_owner', 'organization_admin'],
    auditRequired: true,
  },
  {
    id: 'workspace.read',
    description: 'Read workspace metadata and membership.',
    category: 'Workspace',
    riskLevel: RiskLevels.LOW,
    defaultRoles: [
      'organization_owner',
      'organization_admin',
      'security_admin',
      'workspace_admin',
      'operator',
      'developer',
      'auditor',
      'viewer',
    ],
    auditRequired: true,
  },
  {
    id: 'workspace.manage',
    description: 'Create, update, and administer workspaces.',
    category: 'Workspace',
    riskLevel: RiskLevels.HIGH,
    defaultRoles: [
      'organization_owner',
      'organization_admin',
      'security_admin',
      'workspace_admin',
    ],
    auditRequired: true,
  },
  {
    id: 'team.read',
    description: 'Read teams and team membership.',
    category: 'Identity',
    riskLevel: RiskLevels.LOW,
    defaultRoles: [
      'organization_owner',
      'organization_admin',
      'security_admin',
      'workspace_admin',
      'auditor',
      'viewer',
    ],
    auditRequired: true,
  },
  {
    id: 'team.manage',
    description: 'Create, update, and manage teams.',
    category: 'Identity',
    riskLevel: RiskLevels.HIGH,
    defaultRoles: [
      'organization_owner',
      'organization_admin',
      'security_admin',
      'workspace_admin',
    ],
    auditRequired: true,
  },
  {
    id: 'user.read',
    description: 'Read enterprise users and memberships.',
    category: 'Identity',
    riskLevel: RiskLevels.LOW,
    defaultRoles: [
      'organization_owner',
      'organization_admin',
      'security_admin',
      'workspace_admin',
      'auditor',
      'viewer',
    ],
    auditRequired: true,
  },
  {
    id: 'user.manage',
    description: 'Create, update, suspend, and assign enterprise users.',
    category: 'Identity',
    riskLevel: RiskLevels.HIGH,
    defaultRoles: [
      'organization_owner',
      'organization_admin',
      'security_admin',
      'workspace_admin',
    ],
    auditRequired: true,
  },
  {
    id: 'service_account.read',
    description: 'Read service accounts and their scopes.',
    category: 'Identity',
    riskLevel: RiskLevels.MEDIUM,
    defaultRoles: ['organization_owner', 'organization_admin', 'security_admin', 'auditor'],
    auditRequired: true,
  },
  {
    id: 'service_account.manage',
    description: 'Create, rotate, suspend, and scope service accounts.',
    category: 'Identity',
    riskLevel: RiskLevels.CRITICAL,
    defaultRoles: ['organization_owner', 'organization_admin', 'security_admin'],
    auditRequired: true,
  },
  {
    id: 'role.read',
    description: 'Read built-in and custom roles.',
    category: 'Authorization',
    riskLevel: RiskLevels.LOW,
    defaultRoles: [
      'organization_owner',
      'organization_admin',
      'security_admin',
      'workspace_admin',
      'auditor',
      'viewer',
    ],
    auditRequired: true,
  },
  {
    id: 'role.manage',
    description: 'Create and update custom role definitions.',
    category: 'Authorization',
    riskLevel: RiskLevels.CRITICAL,
    defaultRoles: ['organization_owner', 'organization_admin', 'security_admin'],
    auditRequired: true,
  },
  {
    id: 'permission.read',
    description: 'Inspect the permission registry and metadata.',
    category: 'Authorization',
    riskLevel: RiskLevels.LOW,
    defaultRoles: [
      'organization_owner',
      'organization_admin',
      'security_admin',
      'workspace_admin',
      'auditor',
      'viewer',
    ],
    auditRequired: true,
  },
  {
    id: 'passport.read',
    description: 'Read Agent Passport metadata.',
    category: 'Passport',
    riskLevel: RiskLevels.LOW,
    defaultRoles: [
      'organization_owner',
      'organization_admin',
      'workspace_admin',
      'operator',
      'developer',
      'auditor',
      'viewer',
    ],
    auditRequired: true,
  },
  {
    id: 'passport.create',
    description: 'Create and update Agent Passports and install keys.',
    category: 'Passport',
    riskLevel: RiskLevels.HIGH,
    defaultRoles: ['organization_owner', 'organization_admin', 'workspace_admin', 'developer'],
    auditRequired: true,
  },
  {
    id: 'passport.delete',
    description: 'Suspend, revoke, or delete Agent Passport access.',
    category: 'Passport',
    riskLevel: RiskLevels.CRITICAL,
    defaultRoles: ['organization_owner', 'organization_admin', 'workspace_admin'],
    auditRequired: true,
  },
  {
    id: 'connection.read',
    description: 'Read workspace connection metadata.',
    category: 'Connection',
    riskLevel: RiskLevels.LOW,
    defaultRoles: [
      'organization_owner',
      'organization_admin',
      'workspace_admin',
      'operator',
      'developer',
      'auditor',
      'viewer',
    ],
    auditRequired: true,
  },
  {
    id: 'connection.create',
    description: 'Resolve install keys and create workspace connections.',
    category: 'Connection',
    riskLevel: RiskLevels.HIGH,
    defaultRoles: ['organization_owner', 'organization_admin', 'workspace_admin', 'developer'],
    auditRequired: true,
  },
  {
    id: 'connection.invoke',
    description: 'Invoke a connected Agent Passport capability.',
    category: 'Connection',
    riskLevel: RiskLevels.HIGH,
    defaultRoles: ['organization_owner', 'organization_admin', 'workspace_admin', 'operator', 'developer'],
    auditRequired: true,
  },
  {
    id: 'connection.delete',
    description: 'Disconnect or remove workspace connections.',
    category: 'Connection',
    riskLevel: RiskLevels.CRITICAL,
    defaultRoles: ['organization_owner', 'organization_admin', 'workspace_admin'],
    auditRequired: true,
  },
  {
    id: 'credential.read',
    description: 'Read credential metadata without exposing secrets.',
    category: 'Credential',
    riskLevel: RiskLevels.HIGH,
    defaultRoles: ['organization_owner', 'organization_admin', 'security_admin', 'auditor'],
    auditRequired: true,
  },
  {
    id: 'credential.rotate',
    description: 'Create, replace, revoke, or rotate runtime credentials.',
    category: 'Credential',
    riskLevel: RiskLevels.CRITICAL,
    defaultRoles: [
      'organization_owner',
      'organization_admin',
      'security_admin',
      'workspace_admin',
      'developer',
    ],
    auditRequired: true,
  },
  {
    id: 'audit.read',
    description: 'Read redacted audit events.',
    category: 'Audit',
    riskLevel: RiskLevels.HIGH,
    defaultRoles: ['organization_owner', 'organization_admin', 'security_admin', 'auditor'],
    auditRequired: true,
  },
  {
    id: 'invocation.read',
    description: 'Read invocation state, attempts, and safe metadata.',
    category: 'Invocation',
    riskLevel: RiskLevels.LOW,
    defaultRoles: [
      'organization_owner',
      'organization_admin',
      'workspace_admin',
      'operator',
      'developer',
      'auditor',
      'viewer',
    ],
    auditRequired: true,
  },
  {
    id: 'invocation.retry',
    description: 'Request safe manual invocation retry.',
    category: 'Invocation',
    riskLevel: RiskLevels.HIGH,
    defaultRoles: ['organization_owner', 'organization_admin', 'workspace_admin', 'operator'],
    auditRequired: true,
  },
  {
    id: 'invocation.cancel',
    description: 'Cancel or resolve invocation control state.',
    category: 'Invocation',
    riskLevel: RiskLevels.HIGH,
    defaultRoles: ['organization_owner', 'organization_admin', 'workspace_admin', 'operator'],
    auditRequired: true,
  },
  {
    id: 'worker.read',
    description: 'Read aggregate runtime worker and durable queue health.',
    category: 'Operations',
    riskLevel: RiskLevels.MEDIUM,
    defaultRoles: ['organization_owner', 'organization_admin', 'workspace_admin', 'operator', 'auditor'],
    auditRequired: true,
  },
  {
    id: 'worker.manage',
    description: 'Run bounded durable worker recovery and reconciliation controls.',
    category: 'Operations',
    riskLevel: RiskLevels.CRITICAL,
    defaultRoles: ['organization_owner', 'organization_admin', 'workspace_admin', 'operator'],
    auditRequired: true,
  },
  {
    id: 'operations.read',
    description: 'Read operational summaries, alerts, and safety metrics.',
    category: 'Operations',
    riskLevel: RiskLevels.MEDIUM,
    defaultRoles: [
      'organization_owner',
      'organization_admin',
      'workspace_admin',
      'operator',
      'auditor',
      'viewer',
    ],
    auditRequired: true,
  },
  {
    id: 'operations.manage',
    description: 'Acknowledge alerts and run bounded operational controls.',
    category: 'Operations',
    riskLevel: RiskLevels.HIGH,
    defaultRoles: ['organization_owner', 'organization_admin', 'workspace_admin', 'operator'],
    auditRequired: true,
  },
  {
    id: 'policy.read',
    description: 'Read policy placeholders and future policy attachment points.',
    category: 'Authorization',
    riskLevel: RiskLevels.LOW,
    defaultRoles: ['organization_owner', 'organization_admin', 'security_admin', 'auditor'],
    auditRequired: true,
  },
  {
    id: 'policy.manage',
    description: 'Reserve policy management for future conditional policy engines.',
    category: 'Authorization',
    riskLevel: RiskLevels.CRITICAL,
    defaultRoles: ['organization_owner', 'organization_admin', 'security_admin'],
    auditRequired: true,
  },
].map((permission) =>
  Object.freeze({
    registryId: PERMISSION_REGISTRY_ID,
    registryVersion: PERMISSION_REGISTRY_VERSION,
    ...permission,
  }),
);

const permissionsById = new Map(permissionDefinitions.map((permission) => [permission.id, permission]));

function getPermission(permissionId) {
  return permissionsById.get(permissionId);
}

function hasPermission(permissionId) {
  return permissionsById.has(permissionId);
}

function listPermissions() {
  return permissionDefinitions.map((permission) => ({ ...permission }));
}

function getPermissionRegistry() {
  return {
    id: PERMISSION_REGISTRY_ID,
    name: `Permission Registry v${PERMISSION_REGISTRY_VERSION}`,
    version: PERMISSION_REGISTRY_VERSION,
    permissions: listPermissions(),
  };
}

module.exports = {
  PERMISSION_REGISTRY_ID,
  PERMISSION_REGISTRY_VERSION,
  RiskLevels,
  getPermission,
  getPermissionRegistry,
  hasPermission,
  listPermissions,
};
