const POLICY_SCHEMA_VERSION = 1;
const ATTRIBUTE_REGISTRY_VERSION = 3;

const POLICY_STATUSES = Object.freeze(['DRAFT', 'ACTIVE', 'RETIRED']);
const POLICY_EFFECTS = Object.freeze(['ALLOW', 'DENY']);
const LOGICAL_OPERATORS = Object.freeze(['ALL', 'ANY', 'NOT']);
const COMPARISON_OPERATORS = Object.freeze([
  'EQUALS',
  'NOT_EQUALS',
  'IN',
  'NOT_IN',
  'EXISTS',
  'NOT_EXISTS',
  'LESS_THAN',
  'LESS_THAN_OR_EQUAL',
  'GREATER_THAN',
  'GREATER_THAN_OR_EQUAL',
  'STARTS_WITH',
  'ENDS_WITH',
  'CONTAINS',
]);

const POLICY_LIMITS = Object.freeze({
  maxDepth: 8,
  maxNodes: 100,
  maxArrayItems: 100,
  maxStringLength: 2_048,
  maxDocumentBytes: 128 * 1024,
  maxTargetItems: 100,
});

const POLICY_REASON_CODES = Object.freeze({
  RBAC_PERMISSION_DENIED: 'RBAC_PERMISSION_DENIED',
  POLICY_EXPLICIT_DENY: 'POLICY_EXPLICIT_DENY',
  POLICY_ALLOW_CONDITION_NOT_MET: 'POLICY_ALLOW_CONDITION_NOT_MET',
  POLICY_ALLOW_MATCHED: 'POLICY_ALLOW_MATCHED',
  NO_APPLICABLE_POLICY: 'NO_APPLICABLE_POLICY',
  POLICY_EVALUATION_ERROR: 'POLICY_EVALUATION_ERROR',
  POLICY_ATTRIBUTE_UNAVAILABLE: 'POLICY_ATTRIBUTE_UNAVAILABLE',
  POLICY_INVALID: 'POLICY_INVALID',
  TENANT_SCOPE_MISMATCH: 'TENANT_SCOPE_MISMATCH',
});

module.exports = {
  ATTRIBUTE_REGISTRY_VERSION,
  COMPARISON_OPERATORS,
  LOGICAL_OPERATORS,
  POLICY_EFFECTS,
  POLICY_LIMITS,
  POLICY_REASON_CODES,
  POLICY_SCHEMA_VERSION,
  POLICY_STATUSES,
};
