const SECRET_SCHEMA_VERSION = 1;
const SECRET_VERSION_SCHEMA_VERSION = 1;
const ENCRYPTION_AAD_VERSION = 1;

const SECRET_STATUSES = Object.freeze(['ACTIVE', 'DISABLED', 'REVOKED', 'EXPIRED', 'DESTROYED']);
const SECRET_VERSION_STATUSES = Object.freeze([
  'PENDING',
  'ACTIVE',
  'PREVIOUS',
  'RETIRED',
  'REVOKED',
  'EXPIRED',
  'DESTROYED',
]);
const SECRET_VALIDATION_STATUSES = Object.freeze(['PENDING', 'VALIDATED', 'INVALID', 'UNKNOWN']);
const SECRET_HEALTH_STATUSES = Object.freeze([
  'UNKNOWN',
  'HEALTHY',
  'DEGRADED',
  'INVALID',
  'EXPIRED',
  'REVOKED',
  'UNAVAILABLE',
]);
const BINDING_STATUSES = Object.freeze(['ACTIVE', 'DISABLED', 'REVOKED']);
const LEASE_STATUSES = Object.freeze(['ISSUED', 'CONSUMED', 'EXPIRED', 'REVOKED', 'REJECTED']);
const ROTATION_STAGES = Object.freeze([
  'REQUESTED',
  'NEW_VERSION_STORED',
  'VALIDATING',
  'VALIDATED',
  'ACTIVATING',
  'ACTIVE',
  'GRACE_PERIOD',
  'OLD_VERSION_RETIRED',
  'COMPLETED',
  'FAILED',
  'RECOVERY_REQUIRED',
]);
const REWRAP_STATUSES = Object.freeze([
  'PENDING',
  'RUNNING',
  'COMPLETED',
  'COMPLETED_WITH_FAILURES',
  'FAILED',
]);
const CREDENTIAL_TYPES = Object.freeze([
  'api_key',
  'bearer_token',
  'oauth2',
  'delegated_runtime_access',
  'client_secret',
  'refresh_token',
  'webhook_signing_secret',
]);
const OWNERSHIP_SCOPES = Object.freeze(['ORGANIZATION', 'WORKSPACE']);

const SECRET_LIMITS = Object.freeze({
  maximumPlaintextBytes: 64 * 1024,
  maximumNameLength: 200,
  maximumDescriptionLength: 2_000,
  defaultLeaseTtlMs: 30_000,
  maximumLeaseTtlMs: 5 * 60_000,
  leaseEvidenceRetentionMs: 24 * 60 * 60_000,
  maximumGracePeriodSeconds: 7 * 24 * 60 * 60,
  maximumRewrapBatchSize: 100,
});

const SECRET_AUDIT_EVENTS = Object.freeze({
  CREATED: 'SECRET_CREATED',
  VERSION_ADDED: 'SECRET_VERSION_ADDED',
  VERSION_VALIDATED: 'SECRET_VERSION_VALIDATED',
  VERSION_ACTIVATED: 'SECRET_VERSION_ACTIVATED',
  ROTATION_STARTED: 'SECRET_ROTATION_STARTED',
  ROTATION_COMPLETED: 'SECRET_ROTATION_COMPLETED',
  ROTATION_FAILED: 'SECRET_ROTATION_FAILED',
  REVOKED: 'SECRET_REVOKED',
  EXPIRED: 'SECRET_EXPIRED',
  DISABLED: 'SECRET_DISABLED',
  DESTROYED: 'SECRET_DESTROYED',
  BOUND: 'SECRET_BOUND',
  UNBOUND: 'SECRET_UNBOUND',
  RUNTIME_ACCESS_ALLOWED: 'SECRET_RUNTIME_ACCESS_ALLOWED',
  RUNTIME_ACCESS_DENIED: 'SECRET_RUNTIME_ACCESS_DENIED',
  REWRAP_STARTED: 'ENCRYPTION_REWRAP_STARTED',
  REWRAP_COMPLETED: 'ENCRYPTION_REWRAP_COMPLETED',
  REWRAP_FAILED: 'ENCRYPTION_REWRAP_FAILED',
});

module.exports = {
  BINDING_STATUSES,
  CREDENTIAL_TYPES,
  ENCRYPTION_AAD_VERSION,
  LEASE_STATUSES,
  OWNERSHIP_SCOPES,
  REWRAP_STATUSES,
  ROTATION_STAGES,
  SECRET_AUDIT_EVENTS,
  SECRET_HEALTH_STATUSES,
  SECRET_LIMITS,
  SECRET_SCHEMA_VERSION,
  SECRET_STATUSES,
  SECRET_VALIDATION_STATUSES,
  SECRET_VERSION_SCHEMA_VERSION,
  SECRET_VERSION_STATUSES,
};
